
package org.smpte_ra.schemas.st2071._2014.session;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-09T14:41:07.271-04:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "LockNotFound", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/session")
public class LockNotFoundFault extends java.lang.Exception {
    
    private org.smpte_ra.schemas.st2071._2014.session.LockNotFound lockNotFound;

    public LockNotFoundFault() {
        super();
    }
    
    public LockNotFoundFault(String message) {
        super(message);
    }
    
    public LockNotFoundFault(String message, Throwable cause) {
        super(message, cause);
    }

    public LockNotFoundFault(String message, org.smpte_ra.schemas.st2071._2014.session.LockNotFound lockNotFound) {
        super(message);
        this.lockNotFound = lockNotFound;
    }

    public LockNotFoundFault(String message, org.smpte_ra.schemas.st2071._2014.session.LockNotFound lockNotFound, Throwable cause) {
        super(message, cause);
        this.lockNotFound = lockNotFound;
    }

    public org.smpte_ra.schemas.st2071._2014.session.LockNotFound getFaultInfo() {
        return this.lockNotFound;
    }
}
