
package org.smpte_ra.schemas.st2071._2014.session;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-09T14:41:07.465-04:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "SessionNotFound", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/session")
public class SessionNotFoundFault extends java.lang.Exception {
    
    private org.smpte_ra.schemas.st2071._2014.session.SessionNotFound sessionNotFound;

    public SessionNotFoundFault() {
        super();
    }
    
    public SessionNotFoundFault(String message) {
        super(message);
    }
    
    public SessionNotFoundFault(String message, Throwable cause) {
        super(message, cause);
    }

    public SessionNotFoundFault(String message, org.smpte_ra.schemas.st2071._2014.session.SessionNotFound sessionNotFound) {
        super(message);
        this.sessionNotFound = sessionNotFound;
    }

    public SessionNotFoundFault(String message, org.smpte_ra.schemas.st2071._2014.session.SessionNotFound sessionNotFound, Throwable cause) {
        super(message, cause);
        this.sessionNotFound = sessionNotFound;
    }

    public org.smpte_ra.schemas.st2071._2014.session.SessionNotFound getFaultInfo() {
        return this.sessionNotFound;
    }
}
