
package org.smpte_ra.schemas.st2071._2014.session;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SessionNotFound", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/session")
public class SessionNotFoundFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SessionNotFound faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SessionNotFoundFault(String message, SessionNotFound faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SessionNotFoundFault(String message, SessionNotFound faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.smpte_ra.schemas.st2071._2014.session.SessionNotFound
     */
    public SessionNotFound getFaultInfo() {
        return faultInfo;
    }

}
