
package org.smpte_ra.schemas.st2071._2014.service;

import javax.xml.ws.WebFault;
import org.smpte_ra.schemas.st2071._2014.query.InvalidQuery;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidQuery", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/query")
public class InvalidQueryFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidQuery faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InvalidQueryFault(String message, InvalidQuery faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InvalidQueryFault(String message, InvalidQuery faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.smpte_ra.schemas.st2071._2014.query.InvalidQuery
     */
    public InvalidQuery getFaultInfo() {
        return faultInfo;
    }

}
