
package org.smpte_ra.schemas.st2071._2014.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-09T14:42:23.269-04:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "ServiceException", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/service")
public class ServiceExceptionFault extends java.lang.Exception {
    
    private org.smpte_ra.schemas.st2071._2014.service.ServiceException serviceException;

    public ServiceExceptionFault() {
        super();
    }
    
    public ServiceExceptionFault(String message) {
        super(message);
    }
    
    public ServiceExceptionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceExceptionFault(String message, org.smpte_ra.schemas.st2071._2014.service.ServiceException serviceException) {
        super(message);
        this.serviceException = serviceException;
    }

    public ServiceExceptionFault(String message, org.smpte_ra.schemas.st2071._2014.service.ServiceException serviceException, Throwable cause) {
        super(message, cause);
        this.serviceException = serviceException;
    }

    public org.smpte_ra.schemas.st2071._2014.service.ServiceException getFaultInfo() {
        return this.serviceException;
    }
}
