
package org.smpte_ra.schemas.st2071._2014.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ServiceNotFound", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/service")
public class ServiceNotFoundFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServiceNotFound faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ServiceNotFoundFault(String message, ServiceNotFound faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ServiceNotFoundFault(String message, ServiceNotFound faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.smpte_ra.schemas.st2071._2014.service.ServiceNotFound
     */
    public ServiceNotFound getFaultInfo() {
        return faultInfo;
    }

}
