'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Mono Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Explicit On
Option Strict On


'
' This source code was auto-generated by Mono Web Services Description Language Utility
'

'''<remarks/>
<System.Web.Services.WebServiceBinding(Name:="AcquirablePort", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Public Class AcquirableHTTPBinding
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Public Sub New()
        MyBase.New
        Me.Url = "http://localhost:8088/Acquirable"
    End Sub
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/device/control/Acquirable/Acquired", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function getAcquired(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> ByVal getAcquired As EmptyRequest) As <System.Xml.Serialization.XmlElementAttribute("getAcquiredResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> BooleanResponse
        Dim results As Object() = Me.Invoke("getAcquired", New Object() {getAcquired})
        Return CType(results(0), BooleanResponse)
    End Function
    
    Public Function BegingetAcquired(ByVal getAcquired As EmptyRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getAcquired", New Object() {getAcquired}, callback, asyncState)
    End Function
    
    Public Function EndgetAcquired(ByVal asyncResult As System.IAsyncResult) As BooleanResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), BooleanResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/device/control/Acquirable/AcquiredBy", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function getAcquiredBy(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> ByVal getAcquiredBy As EmptyRequest) As <System.Xml.Serialization.XmlElementAttribute("getAcquiredByResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> getAcquiredByResponse
        Dim results As Object() = Me.Invoke("getAcquiredBy", New Object() {getAcquiredBy})
        Return CType(results(0), getAcquiredByResponse)
    End Function
    
    Public Function BegingetAcquiredBy(ByVal getAcquiredBy As EmptyRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getAcquiredBy", New Object() {getAcquiredBy}, callback, asyncState)
    End Function
    
    Public Function EndgetAcquiredBy(ByVal asyncResult As System.IAsyncResult) As getAcquiredByResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), getAcquiredByResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/device/control/Acquirable/acquire", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function acquire(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> ByVal acquire As acquire) As <System.Xml.Serialization.XmlElementAttribute("acquireResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> URIResponse
        Dim results As Object() = Me.Invoke("acquire", New Object() {acquire})
        Return CType(results(0), URIResponse)
    End Function
    
    Public Function Beginacquire(ByVal acquire As acquire, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("acquire", New Object() {acquire}, callback, asyncState)
    End Function
    
    Public Function Endacquire(ByVal asyncResult As System.IAsyncResult) As URIResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), URIResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/device/control/Acquirable/release", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function release(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> ByVal release As URIRequest) As <System.Xml.Serialization.XmlElementAttribute("releaseResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> BooleanResponse
        Dim results As Object() = Me.Invoke("release", New Object() {release})
        Return CType(results(0), BooleanResponse)
    End Function
    
    Public Function Beginrelease(ByVal release As URIRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("release", New Object() {release}, callback, asyncState)
    End Function
    
    Public Function Endrelease(ByVal asyncResult As System.IAsyncResult) As BooleanResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), BooleanResponse)
    End Function
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session"),  _
 System.Xml.Serialization.XmlRootAttribute("getLockedBy", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")>  _
Public Class EmptyRequest
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session"),  _
 System.Xml.Serialization.XmlRootAttribute("unlockResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")>  _
Public Class BooleanResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public [Boolean] As Boolean
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")>  _
Public Class getAcquiredByResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Sessions As Session()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")>  _
Public Class Session
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="", DataType:="anyURI")>  _
    Public id As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public is_lock As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnore()>  _
    Public is_lockSpecified As Boolean
    
    '''<remarks/>
    Public Who As String
    
    '''<remarks/>
    Public Name As String
    
    '''<remarks/>
    Public AcquiredAt As DateTime
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlRootAttribute("AcquiredAt", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")>  _
Public Class DateTime
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Value As Date
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")>  _
Public Class acquire
    
    '''<remarks/>
    Public Name As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session"),  _
 System.Xml.Serialization.XmlRootAttribute("takeResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")>  _
Public Class URIResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public URI As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session"),  _
 System.Xml.Serialization.XmlRootAttribute("approve", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")>  _
Public Class URIRequest
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public URI As String
End Class

'''<remarks/>
<System.Web.Services.WebServiceBinding(Name:="LockablePort", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Public Class LockableHTTPBinding
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Public Sub New()
        MyBase.New
        Me.Url = "http://localhost:8088/Lockable"
    End Sub
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/device/control/Lockable/Locked", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function getLocked(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> ByVal getLocked As EmptyRequest) As <System.Xml.Serialization.XmlElementAttribute("getLockedResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> BooleanResponse
        Dim results As Object() = Me.Invoke("getLocked", New Object() {getLocked})
        Return CType(results(0), BooleanResponse)
    End Function
    
    Public Function BegingetLocked(ByVal getLocked As EmptyRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getLocked", New Object() {getLocked}, callback, asyncState)
    End Function
    
    Public Function EndgetLocked(ByVal asyncResult As System.IAsyncResult) As BooleanResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), BooleanResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/device/control/Lockable/LockedBy", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function getLockedBy(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> ByVal getLockedBy As EmptyRequest) As <System.Xml.Serialization.XmlElementAttribute("getLockedByResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> getLockedByResponse
        Dim results As Object() = Me.Invoke("getLockedBy", New Object() {getLockedBy})
        Return CType(results(0), getLockedByResponse)
    End Function
    
    Public Function BegingetLockedBy(ByVal getLockedBy As EmptyRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getLockedBy", New Object() {getLockedBy}, callback, asyncState)
    End Function
    
    Public Function EndgetLockedBy(ByVal asyncResult As System.IAsyncResult) As getLockedByResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), getLockedByResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/device/control/Lockable/lock", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function lock(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> ByVal lock As lock) As <System.Xml.Serialization.XmlElementAttribute("lockResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> URIResponse
        Dim results As Object() = Me.Invoke("lock", New Object() {lock})
        Return CType(results(0), URIResponse)
    End Function
    
    Public Function Beginlock(ByVal lock As lock, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("lock", New Object() {lock}, callback, asyncState)
    End Function
    
    Public Function Endlock(ByVal asyncResult As System.IAsyncResult) As URIResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), URIResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/device/control/Lockable/unlock", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function unlock(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> ByVal unlock As URIRequest) As <System.Xml.Serialization.XmlElementAttribute("unlockResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> BooleanResponse
        Dim results As Object() = Me.Invoke("unlock", New Object() {unlock})
        Return CType(results(0), BooleanResponse)
    End Function
    
    Public Function Beginunlock(ByVal unlock As URIRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("unlock", New Object() {unlock}, callback, asyncState)
    End Function
    
    Public Function Endunlock(ByVal asyncResult As System.IAsyncResult) As BooleanResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), BooleanResponse)
    End Function
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")>  _
Public Class getLockedByResponse
    
    '''<remarks/>
    Public Session As Session
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")>  _
Public Class lock
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public SessionID As String
    
    '''<remarks/>
    Public Name As String
End Class

'''<remarks/>
<System.Web.Services.WebServiceBinding(Name:="RequestablePort", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Public Class RequestableHTTPBinding
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Public Sub New()
        MyBase.New
        Me.Url = "http://localhost:8088/Requestable"
    End Sub
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/session/Requestable/approve", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function approve(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> ByVal approve As URIRequest) As <System.Xml.Serialization.XmlElementAttribute("approveResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> EmptyResponse
        Dim results As Object() = Me.Invoke("approve", New Object() {approve})
        Return CType(results(0), EmptyResponse)
    End Function
    
    Public Function Beginapprove(ByVal approve As URIRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("approve", New Object() {approve}, callback, asyncState)
    End Function
    
    Public Function Endapprove(ByVal asyncResult As System.IAsyncResult) As EmptyResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), EmptyResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/session/Requestable/deny", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function deny(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> ByVal deny As deny) As <System.Xml.Serialization.XmlElementAttribute("denyResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> EmptyResponse
        Dim results As Object() = Me.Invoke("deny", New Object() {deny})
        Return CType(results(0), EmptyResponse)
    End Function
    
    Public Function Begindeny(ByVal deny As deny, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("deny", New Object() {deny}, callback, asyncState)
    End Function
    
    Public Function Enddeny(ByVal asyncResult As System.IAsyncResult) As EmptyResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), EmptyResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/session/Requestable/request", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function request(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> ByVal request As RequestParameters) As <System.Xml.Serialization.XmlElementAttribute("requestResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> URIResponse
        Dim results As Object() = Me.Invoke("request", New Object() {request})
        Return CType(results(0), URIResponse)
    End Function
    
    Public Function Beginrequest(ByVal request As RequestParameters, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("request", New Object() {request}, callback, asyncState)
    End Function
    
    Public Function Endrequest(ByVal asyncResult As System.IAsyncResult) As URIResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), URIResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/session/Requestable/take", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function take(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> ByVal take As RequestParameters) As <System.Xml.Serialization.XmlElementAttribute("takeResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")> URIResponse
        Dim results As Object() = Me.Invoke("take", New Object() {take})
        Return CType(results(0), URIResponse)
    End Function
    
    Public Function Begintake(ByVal take As RequestParameters, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("take", New Object() {take}, callback, asyncState)
    End Function
    
    Public Function Endtake(ByVal asyncResult As System.IAsyncResult) As URIResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), URIResponse)
    End Function
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session"),  _
 System.Xml.Serialization.XmlRootAttribute("denyResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")>  _
Public Class EmptyResponse
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")>  _
Public Class deny
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public RequestID As String
    
    '''<remarks/>
    Public Message As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session"),  _
 System.Xml.Serialization.XmlRootAttribute("take", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/session")>  _
Public Class RequestParameters
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public ID As String
    
    '''<remarks/>
    Public Name As String
    
    '''<remarks/>
    Public Message As String
End Class
