'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Mono Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Explicit On
Option Strict On


'
' This source code was auto-generated by Mono Web Services Description Language Utility
'

'''<remarks/>
<System.Web.Services.WebServiceBinding(Name:="ModeSupportPort", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Public Class DeviceService
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Public Sub New()
        MyBase.New
        Me.Url = "http://localhost:8088/ModeSupport"
    End Sub
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/mode/ModeSupport/Modes", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function getModes(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")> ByVal getModes As getModes) As <System.Xml.Serialization.XmlElementAttribute("getModesResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")> getModesResponse
        Dim results As Object() = Me.Invoke("getModes", New Object() {getModes})
        Return CType(results(0), getModesResponse)
    End Function
    
    Public Function BegingetModes(ByVal getModes As getModes, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getModes", New Object() {getModes}, callback, asyncState)
    End Function
    
    Public Function EndgetModes(ByVal asyncResult As System.IAsyncResult) As getModesResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), getModesResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/mode/ModeSupport/ActiveMode", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function getActiveMode(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")> ByVal getActiveMode As getActiveMode) As <System.Xml.Serialization.XmlElementAttribute("getActiveModeResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")> getActiveModeResponse
        Dim results As Object() = Me.Invoke("getActiveMode", New Object() {getActiveMode})
        Return CType(results(0), getActiveModeResponse)
    End Function
    
    Public Function BegingetActiveMode(ByVal getActiveMode As getActiveMode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getActiveMode", New Object() {getActiveMode}, callback, asyncState)
    End Function
    
    Public Function EndgetActiveMode(ByVal asyncResult As System.IAsyncResult) As getActiveModeResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), getActiveModeResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/mode/ModeSupport/changeMode", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function changeMode(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")> ByVal changeMode As changeMode) As <System.Xml.Serialization.XmlElementAttribute("changeModeResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")> changeModeResponse
        Dim results As Object() = Me.Invoke("changeMode", New Object() {changeMode})
        Return CType(results(0), changeModeResponse)
    End Function
    
    Public Function BeginchangeMode(ByVal changeMode As changeMode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("changeMode", New Object() {changeMode}, callback, asyncState)
    End Function
    
    Public Function EndchangeMode(ByVal asyncResult As System.IAsyncResult) As changeModeResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), changeModeResponse)
    End Function
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class getModes
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class getModesResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Modes As Mode()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class Mode
    
    '''<remarks/>
    Public Name As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
     System.Xml.Serialization.XmlArrayItem(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable:=false)>  _
    Public Capabilities As Capability()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
Public Class Capability
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UCN As String
    
    '''<remarks/>
    Public Attributes As Map
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity"),  _
     System.Xml.Serialization.XmlArrayItem(ElementName:="URL", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public URLs As String()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlRootAttribute("Attributes", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
Public Class Map
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Keys As Key()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
Public Class Key
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public id As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public type As DATA_TYPE
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Value As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
Public Enum DATA_TYPE
    
    '''<remarks/>
    BOOLEAN
    
    '''<remarks/>
    STRING
    
    '''<remarks/>
    INTEGER
    
    '''<remarks/>
    FLOAT
    
    '''<remarks/>
    DATETIME
    
    '''<remarks/>
    URI
    
    '''<remarks/>
    MAP
    
    '''<remarks/>
    BLOB
End Enum

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class getActiveMode
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class getActiveModeResponse
    
    '''<remarks/>
    Public Mode As Mode
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class changeMode
    
    '''<remarks/>
    Public Mode As Mode
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class changeModeResponse
End Class
