'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Mono Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Explicit On
Option Strict On


'
' This source code was auto-generated by Mono Web Services Description Language Utility
'

'''<remarks/>
<System.Web.Services.WebServiceBinding(Name:="StatusSupportPort", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType([Event]))>  _
Public Class StatusSupportHTTPBinding
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Public Sub New()
        MyBase.New
        Me.Url = "http://localhost:8088/StatusSupport"
    End Sub
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/schemas/st2071/2014/event/StatusSupport/Status", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function getStatus(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")> ByVal getStatus As getStatus) As <System.Xml.Serialization.XmlElementAttribute("getStatusResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")> getStatusResponse
        Dim results As Object() = Me.Invoke("getStatus", New Object() {getStatus})
        Return CType(results(0), getStatusResponse)
    End Function
    
    Public Function BegingetStatus(ByVal getStatus As getStatus, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getStatus", New Object() {getStatus}, callback, asyncState)
    End Function
    
    Public Function EndgetStatus(ByVal asyncResult As System.IAsyncResult) As getStatusResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), getStatusResponse)
    End Function
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class getStatus
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class getStatusResponse
    
    '''<remarks/>
    Public StatusEvent As StatusEvent
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class StatusEvent
    Inherits [Event]
    
    '''<remarks/>
    Public Ready As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public STATUS As STATUS
    
    '''<remarks/>
    Public Message As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
Public Enum STATUS
    
    '''<remarks/>
    OK
    
    '''<remarks/>
    WARNING
    
    '''<remarks/>
    ERROR
End Enum

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(StatusEvent))>  _
Public Class [Event]
    
    '''<remarks/>
    Public Type As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public RN As String
    
    '''<remarks/>
    Public EventTime As DateTime
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlRootAttribute("EventTime", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class DateTime
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Value As Date
End Class

'''<remarks/>
<System.Web.Services.WebServiceBinding(Name:="EventerPort", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType([Event]))>  _
Public Class EventerHTTPBinding
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Public Sub New()
        MyBase.New
        Me.Url = "http://localhost:8088/Eventer"
    End Sub
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/schemas/st2071/2014/eventer/poll", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function poll(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")> ByVal poll As URIParameter) As <System.Xml.Serialization.XmlElementAttribute("pollResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")> pollResponse
        Dim results As Object() = Me.Invoke("poll", New Object() {poll})
        Return CType(results(0), pollResponse)
    End Function
    
    Public Function Beginpoll(ByVal poll As URIParameter, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("poll", New Object() {poll}, callback, asyncState)
    End Function
    
    Public Function Endpoll(ByVal asyncResult As System.IAsyncResult) As pollResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), pollResponse)
    End Function
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Xml.Serialization.XmlRootAttribute("unregistered", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class URIParameter
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public URI As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class pollResponse
    
    '''<remarks/>
    Public [Event] As [Event]
End Class

'''<remarks/>
<System.Web.Services.WebServiceBinding(Name:="EventBroadcasterPort", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType([Event]))>  _
Public Class EventBroadcasterHTTPBinding
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Public Sub New()
        MyBase.New
        Me.Url = "http://localhost:8088/EventBroadcaster"
    End Sub
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/schemas/st2071/2014/eventBroadcaster/registerCallback", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function registerCallback(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")> ByVal registerCallback As URIParameter) As <System.Xml.Serialization.XmlElementAttribute("registerCallbackResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")> registerCallbackResponse
        Dim results As Object() = Me.Invoke("registerCallback", New Object() {registerCallback})
        Return CType(results(0), registerCallbackResponse)
    End Function
    
    Public Function BeginregisterCallback(ByVal registerCallback As URIParameter, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("registerCallback", New Object() {registerCallback}, callback, asyncState)
    End Function
    
    Public Function EndregisterCallback(ByVal asyncResult As System.IAsyncResult) As registerCallbackResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), registerCallbackResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/schemas/st2071/2014/eventBroadcaster/unregisterCallback", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function unregisterCallback(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")> ByVal unregisterCallback As URIParameter) As <System.Xml.Serialization.XmlElementAttribute("unregisterCallbackResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")> unregisterCallbackResponse
        Dim results As Object() = Me.Invoke("unregisterCallback", New Object() {unregisterCallback})
        Return CType(results(0), unregisterCallbackResponse)
    End Function
    
    Public Function BeginunregisterCallback(ByVal unregisterCallback As URIParameter, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("unregisterCallback", New Object() {unregisterCallback}, callback, asyncState)
    End Function
    
    Public Function EndunregisterCallback(ByVal asyncResult As System.IAsyncResult) As unregisterCallbackResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), unregisterCallbackResponse)
    End Function
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class registerCallbackResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public [Boolean] As Boolean
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class unregisterCallbackResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public [Boolean] As Boolean
End Class

'''<remarks/>
<System.Web.Services.WebServiceBinding(Name:="CallbackHandlerPort", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType([Event]))>  _
Public Class CallbackHandlerHTTPBinding
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Public Sub New()
        MyBase.New
        Me.Url = "http://localhost:8088/CallbackHandler"
    End Sub
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/schemas/st2071/2014/event/CallbackHandler/callback", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, OneWay:=true, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Sub callback(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")> ByVal callback As callback)
        Me.Invoke("callback", New Object() {callback})
    End Sub
    
    Public Function Begincallback(ByVal callback As callback, ByVal callback1 As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("callback", New Object() {callback}, callback1, asyncState)
    End Function
    
    Public Sub Endcallback(ByVal asyncResult As System.IAsyncResult)
        Me.EndInvoke(asyncResult)
    End Sub
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/schemas/st2071/2014/event/CallbackHandler/registered", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, OneWay:=true, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Sub registered(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")> ByVal registered As URIParameter)
        Me.Invoke("registered", New Object() {registered})
    End Sub
    
    Public Function Beginregistered(ByVal registered As URIParameter, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("registered", New Object() {registered}, callback, asyncState)
    End Function
    
    Public Sub Endregistered(ByVal asyncResult As System.IAsyncResult)
        Me.EndInvoke(asyncResult)
    End Sub
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/schemas/st2071/2014/event/CallbackHandler/unregistered", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, OneWay:=true, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Sub unregistered(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")> ByVal unregistered As URIParameter)
        Me.Invoke("unregistered", New Object() {unregistered})
    End Sub
    
    Public Function Beginunregistered(ByVal unregistered As URIParameter, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("unregistered", New Object() {unregistered}, callback, asyncState)
    End Function
    
    Public Sub Endunregistered(ByVal asyncResult As System.IAsyncResult)
        Me.EndInvoke(asyncResult)
    End Sub
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class callback
    
    '''<remarks/>
    Public [Event] As [Event]
End Class
