package org.smpte_ra.schemas.st2071._2014.session;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * UCN = urn:smpte:ucn:org.smpte.st2071:acquirable_v1.0
 *         
 *
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-09T14:41:07.739-04:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/session", name = "Acquirable")
@XmlSeeAlso({org.smpte_ra.schemas.st2071._2014.query.ObjectFactory.class, org.smpte_ra.schemas.st2071._2014.mode.ObjectFactory.class, org.smpte_ra.schemas.st2071._2014.media.ObjectFactory.class, org.smpte_ra.schemas.st2071._2014.types.ObjectFactory.class, ObjectFactory.class, org.smpte_ra.schemas.st2071._2014.security.ObjectFactory.class, org.smpte_ra.schemas.st2071._2014.identity.ObjectFactory.class, org.smpte_ra.schemas.st2071._2014.device.ObjectFactory.class, org.smpte_ra.schemas.st2071._2014.event.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Acquirable {

    @WebResult(name = "releaseResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/session", partName = "releaseResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/session/Acquirable/release", output = "http://www.smpte-ra.org/wsdl/st2071/2014/session/Acquirable/releaseResponse", fault = {})
    @WebMethod(action = "http://www.smpte-ra.org/wsdl/st2071/2014/device/control/Acquirable/release")
    public BooleanResponse release(
        @WebParam(partName = "release", name = "release", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/session")
        URIRequest release
    ) throws org.smpte_ra.schemas.st2071._2014.security.SecurityExceptionFault, SessionNotFoundFault, LockedFault, NotAcquiredFault;

    @WebResult(name = "getAcquiredResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/session", partName = "getAcquiredResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/session/Acquirable/Acquired", output = "http://www.smpte-ra.org/wsdl/st2071/2014/session/Acquirable/AcquiredResponse")
    @WebMethod(action = "http://www.smpte-ra.org/wsdl/st2071/2014/device/control/Acquirable/Acquired")
    public BooleanResponse getAcquired(
        @WebParam(partName = "getAcquired", name = "getAcquired", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/session")
        EmptyRequest getAcquired
    );

    @WebResult(name = "getAcquiredByResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/session", partName = "getAcquiredByResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/session/Acquirable/AcquiredBy", output = "http://www.smpte-ra.org/wsdl/st2071/2014/session/Acquirable/AcquiredByResponse")
    @WebMethod(action = "http://www.smpte-ra.org/wsdl/st2071/2014/device/control/Acquirable/AcquiredBy")
    public GetAcquiredByResponse getAcquiredBy(
        @WebParam(partName = "getAcquiredBy", name = "getAcquiredBy", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/session")
        EmptyRequest getAcquiredBy
    );

    @WebResult(name = "acquireResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/session", partName = "acquireResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/session/Acquirable/acquire", output = "http://www.smpte-ra.org/wsdl/st2071/2014/session/Acquirable/acquireResponse", fault = {})
    @WebMethod(action = "http://www.smpte-ra.org/wsdl/st2071/2014/device/control/Acquirable/acquire")
    public URIResponse acquire(
        @WebParam(partName = "acquire", name = "acquire", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/session")
        Acquire acquire
    ) throws LockedFault, NameInUseFault, NotAcquiredFault, TooManySessionsFault, org.smpte_ra.schemas.st2071._2014.security.SecurityExceptionFault;
}
