
package org.smpte_ra.schemas.st2071._2014.session;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Locked", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/session")
public class LockedFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Locked faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public LockedFault(String message, Locked faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public LockedFault(String message, Locked faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.smpte_ra.schemas.st2071._2014.session.Locked
     */
    public Locked getFaultInfo() {
        return faultInfo;
    }

}
