
package org.smpte_ra.schemas.st2071._2014.session;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-09T14:41:07.439-04:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "NotAcquired", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/session")
public class NotAcquiredFault extends java.lang.Exception {
    
    private org.smpte_ra.schemas.st2071._2014.session.NotAcquired notAcquired;

    public NotAcquiredFault() {
        super();
    }
    
    public NotAcquiredFault(String message) {
        super(message);
    }
    
    public NotAcquiredFault(String message, Throwable cause) {
        super(message, cause);
    }

    public NotAcquiredFault(String message, org.smpte_ra.schemas.st2071._2014.session.NotAcquired notAcquired) {
        super(message);
        this.notAcquired = notAcquired;
    }

    public NotAcquiredFault(String message, org.smpte_ra.schemas.st2071._2014.session.NotAcquired notAcquired, Throwable cause) {
        super(message, cause);
        this.notAcquired = notAcquired;
    }

    public org.smpte_ra.schemas.st2071._2014.session.NotAcquired getFaultInfo() {
        return this.notAcquired;
    }
}
