
package org.smpte_ra.schemas.st2071._2014.session;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-09T14:41:07.556-04:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "RequestNotFound", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/session")
public class RequestNotFoundFault extends java.lang.Exception {
    
    private org.smpte_ra.schemas.st2071._2014.session.RequestNotFound requestNotFound;

    public RequestNotFoundFault() {
        super();
    }
    
    public RequestNotFoundFault(String message) {
        super(message);
    }
    
    public RequestNotFoundFault(String message, Throwable cause) {
        super(message, cause);
    }

    public RequestNotFoundFault(String message, org.smpte_ra.schemas.st2071._2014.session.RequestNotFound requestNotFound) {
        super(message);
        this.requestNotFound = requestNotFound;
    }

    public RequestNotFoundFault(String message, org.smpte_ra.schemas.st2071._2014.session.RequestNotFound requestNotFound, Throwable cause) {
        super(message, cause);
        this.requestNotFound = requestNotFound;
    }

    public org.smpte_ra.schemas.st2071._2014.session.RequestNotFound getFaultInfo() {
        return this.requestNotFound;
    }
}
