
package org.smpte_ra.schemas.st2071._2014.session;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-09T14:41:07.542-04:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "TooManySessions", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/session")
public class TooManySessionsFault extends java.lang.Exception {
    
    private org.smpte_ra.schemas.st2071._2014.session.TooManySessions tooManySessions;

    public TooManySessionsFault() {
        super();
    }
    
    public TooManySessionsFault(String message) {
        super(message);
    }
    
    public TooManySessionsFault(String message, Throwable cause) {
        super(message, cause);
    }

    public TooManySessionsFault(String message, org.smpte_ra.schemas.st2071._2014.session.TooManySessions tooManySessions) {
        super(message);
        this.tooManySessions = tooManySessions;
    }

    public TooManySessionsFault(String message, org.smpte_ra.schemas.st2071._2014.session.TooManySessions tooManySessions, Throwable cause) {
        super(message, cause);
        this.tooManySessions = tooManySessions;
    }

    public org.smpte_ra.schemas.st2071._2014.session.TooManySessions getFaultInfo() {
        return this.tooManySessions;
    }
}
