
package org.smpte_ra.schemas.st2071._2014.security;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * 
 *             UCN = urn:smpte:ucn:org.smpte.st2071:authorizer_v1.0
 *         
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Authorizer", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/security")
@XmlSeeAlso({
    org.smpte_ra.schemas.st2071._2014.identity.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.security.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.types.ObjectFactory.class
})
public interface Authorizer {


    /**
     * 
     * @return
     *     returns org.smpte_ra.schemas.st2071._2014.security.Mechanisms
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/security/Authorizer/Mechanisms")
    @WebResult(name = "Mechanisms", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/security")
    @RequestWrapper(localName = "getMechanisms", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/security", className = "org.smpte_ra.schemas.st2071._2014.security.GetMechanisms")
    @ResponseWrapper(localName = "getMechanismsResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/security", className = "org.smpte_ra.schemas.st2071._2014.security.GetMechanismsResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/security/Authorizer/Mechanisms", output = "http://www.smpte-ra.org/wsdl/st2071/2014/security/Authorizer/MechanismsResponse")
    public Mechanisms getMechanisms();

    /**
     * 
     * @param authorize
     * @return
     *     returns org.smpte_ra.schemas.st2071._2014.security.AuthorizeResponse
     * @throws SecurityExceptionFault
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/security/Authorizer/authorize")
    @WebResult(name = "authorizeResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/security", partName = "authorizeResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/security/Authorizer/authorize", output = "http://www.smpte-ra.org/wsdl/st2071/2014/security/Authorizer/authorizeResponse")
    public AuthorizeResponse authorize(
        @WebParam(name = "authorize", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/security", partName = "authorize")
        Authorize authorize)
        throws SecurityExceptionFault
    ;

}
