
package org.smpte_ra.schemas.st2071._2014.security;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-09T14:42:23.246-04:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "SecurityException", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/security")
public class SecurityExceptionFault extends java.lang.Exception {
    
    private org.smpte_ra.schemas.st2071._2014.security.SecurityException securityException;

    public SecurityExceptionFault() {
        super();
    }
    
    public SecurityExceptionFault(String message) {
        super(message);
    }
    
    public SecurityExceptionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public SecurityExceptionFault(String message, org.smpte_ra.schemas.st2071._2014.security.SecurityException securityException) {
        super(message);
        this.securityException = securityException;
    }

    public SecurityExceptionFault(String message, org.smpte_ra.schemas.st2071._2014.security.SecurityException securityException, Throwable cause) {
        super(message, cause);
        this.securityException = securityException;
    }

    public org.smpte_ra.schemas.st2071._2014.security.SecurityException getFaultInfo() {
        return this.securityException;
    }
}
