
package org.smpte_ra.schemas.st2071._2014.mode;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ModeException", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/mode")
public class ModeExceptionFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ModeException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ModeExceptionFault(String message, ModeException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ModeExceptionFault(String message, ModeException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.smpte_ra.schemas.st2071._2014.mode.ModeException
     */
    public ModeException getFaultInfo() {
        return faultInfo;
    }

}
