#!/bin/sh

BASE=`dirname $0`
SOURCE=$BASE;
#XML_SOURCE=$SOURCE/xml;
XML_SOURCE=$BASE/xml;
#GENERATED=$BASE/generated;
#GENERATED_SOURCE=$GENERATED/src;
GENERATED_SOURCE=$BASE;
#GENERATED_JAVA_SOURCE=$GENERATED_SOURCE/java;
GENERATED_JAVA_SOURCE=$GENERATED_SOURCE/java;
GENERATED_DOTNET_SOURCE=$GENERATED_SOURCE/dotnet
#CLASSES=$BASE/classes
CLASSES=$BASE/../../classes

if [ -d $GENERATED ]; then
    echo $GENERATED directory already exists;
else
    echo creating directory $GENERATED;
    mkdir $GENERATED
fi

if [ -d $GENERATED_SOURCE ]; then
    echo $GENERATED_SOURCE directory already exists;
else
    echo creating directory $GENERATED_SOURCE;
    mkdir $GENERATED_SOURCE
fi

if [ -d $GENERATED_JAVA_SOURCE ]; then
    echo $GENERATED_JAVA_SOURCE directory already exists;
else
    echo creating directory $GENERATED_JAVA_SOURCE;
    mkdir $GENERATED_JAVA_SOURCE
fi

if [ -d $GENERATED_DOTNET_SOURCE ]; then
    echo $GENERATED_DOTNET_SOURCE directory already exists;
else
    echo creating directory $GENERATED_DOTNET_SOURCE;
    mkdir $GENERATED_DOTNET_SOURCE
fi

if [ -d $CLASSES ]; then
    echo $CLASSES directory already exists;
else
    echo creating directory $CLASSES;
    mkdir $CLASSES
fi

echo Importing $XML_SOURCE/device_services.wsdl
wsimport $XML_SOURCE/device_services.wsdl -extension -s $GENERATED_JAVA_SOURCE -d $CLASSES
echo Importing device.event_services.wsdl
wsimport $XML_SOURCE/device.event_services.wsdl -extension -s $GENERATED_JAVA_SOURCE -d $CLASSES
echo Importing device.control_services.wsdl
wsimport $XML_SOURCE/device.control_services.wsdl -extension -s $GENERATED_JAVA_SOURCE -d $CLASSES
echo Importing device.mode_services.wsdl
wsimport $XML_SOURCE/device.mode_services.wsdl -extension -s $GENERATED_JAVA_SOURCE -d $CLASSES
echo Importing media_services.wsdl
wsimport $XML_SOURCE/media_services.wsdl -extension -s $GENERATED_JAVA_SOURCE -d $CLASSES 
echo Importing security_services.wsdl
wsimport $XML_SOURCE/security_services.wsdl -extension -s $GENERATED_JAVA_SOURCE -d $CLASSES
echo Importing service_services.wsdl
wsimport $XML_SOURCE/service_services.wsdl -extension -s $GENERATED_JAVA_SOURCE -d $CLASSES
wsdl1 -username:posicks -password:35vn321 -language:CS -out:$GENERATED_DOTNET_SOURCE/device_services_v1.cs $XML_SOURCE/device_services.wsdl
wsdl1 -username:posicks -password:35vn321 -language:CS -out:$GENERATED_DOTNET_SOURCE/device.event_services_v1.cs $XML_SOURCE/device.event_services.wsdl
wsdl1 -username:posicks -password:35vn321 -language:CS -out:$GENERATED_DOTNET_SOURCE/device.control_services_v1.cs $XML_SOURCE/device.control_services.wsdl
wsdl1 -username:posicks -password:35vn321 -language:CS -out:$GENERATED_DOTNET_SOURCE/device.mode_services_v1.cs $XML_SOURCE/device.mode_services.wsdl
wsdl1 -username:posicks -password:35vn321 -language:CS -out:$GENERATED_DOTNET_SOURCE/media_services_v1.cs $XML_SOURCE/media_services.wsdl
wsdl1 -username:posicks -password:35vn321 -language:CS -out:$GENERATED_DOTNET_SOURCE/security_services_v1.cs $XML_SOURCE/security_services.wsdl
wsdl1 -username:posicks -password:35vn321 -language:CS -out:$GENERATED_DOTNET_SOURCE/service_services_v1.cs $XML_SOURCE/service_services.wsdl
wsdl1 -username:posicks -password:35vn321 -language:VB -out:$GENERATED_DOTNET_SOURCE/device_services_v1.vb $XML_SOURCE/device_services.wsdl
wsdl1 -username:posicks -password:35vn321 -language:VB -out:$GENERATED_DOTNET_SOURCE/device.event_services_v1.vb $XML_SOURCE/device.event_services.wsdl
wsdl1 -username:posicks -password:35vn321 -language:VB -out:$GENERATED_DOTNET_SOURCE/device.control_services_v1.vb $XML_SOURCE/device.control_services.wsdl
wsdl1 -username:posicks -password:35vn321 -language:VB -out:$GENERATED_DOTNET_SOURCE/device.mode_services_v1.vb $XML_SOURCE/device.mode_services.wsdl
wsdl1 -username:posicks -password:35vn321 -language:VB -out:$GENERATED_DOTNET_SOURCE/media_services_v1.vb $XML_SOURCE/media_services.wsdl
wsdl1 -username:posicks -password:35vn321 -language:VB -out:$GENERATED_DOTNET_SOURCE/security_services_v1.vb $XML_SOURCE/security_services.wsdl
wsdl1 -username:posicks -password:35vn321 -language:VB -out:$GENERATED_DOTNET_SOURCE/service_services_v1.vb $XML_SOURCE/service_services.wsdl
