
package org.smpte_ra.schemas.st2071._2014.device;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.smpte_ra.schemas.st2071._2014.identity.URLs;
import org.smpte_ra.schemas.st2071._2014.types.Capabilities;
import org.smpte_ra.schemas.st2071._2014.types.Map;


/**
 * 
 *             UCN = urn:smpte:ucn:org.smpte.st2071:device_v1.0
 *         
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Device", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device")
@XmlSeeAlso({
    org.smpte_ra.schemas.st2071._2014.device.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.event.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.identity.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.media.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.mode.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.query.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.security.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.types.ObjectFactory.class
})
public interface Device {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/device/Device/UDN")
    @WebResult(name = "UDN", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/identity")
    @RequestWrapper(localName = "getUDN", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", className = "org.smpte_ra.schemas.st2071._2014.device.GetUDN")
    @ResponseWrapper(localName = "getUDNResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", className = "org.smpte_ra.schemas.st2071._2014.device.GetUDNResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/device/Device/UDN", output = "http://www.smpte-ra.org/wsdl/st2071/2014/device/Device/UDNResponse")
    public String getUDN();

    /**
     * 
     * @return
     *     returns org.smpte_ra.schemas.st2071._2014.identity.URLs
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/device/Device/URLs")
    @WebResult(name = "URLs", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/identity")
    @RequestWrapper(localName = "getURLs", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", className = "org.smpte_ra.schemas.st2071._2014.device.GetURLs")
    @ResponseWrapper(localName = "getURLsResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", className = "org.smpte_ra.schemas.st2071._2014.device.GetURLsResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/device/Device/URLs", output = "http://www.smpte-ra.org/wsdl/st2071/2014/device/Device/URLsResponse")
    public URLs getURLs();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/device/Device/Name")
    @WebResult(name = "String", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/types")
    @RequestWrapper(localName = "getName", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", className = "org.smpte_ra.schemas.st2071._2014.device.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", className = "org.smpte_ra.schemas.st2071._2014.device.GetNameResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/device/Device/Name", output = "http://www.smpte-ra.org/wsdl/st2071/2014/device/Device/NameResponse")
    public String getName();

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/device/Device/Online")
    @WebResult(name = "Boolean", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/types")
    @RequestWrapper(localName = "getOnline", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", className = "org.smpte_ra.schemas.st2071._2014.device.GetOnline")
    @ResponseWrapper(localName = "getOnlineResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", className = "org.smpte_ra.schemas.st2071._2014.device.GetOnlineResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/device/Device/Online", output = "http://www.smpte-ra.org/wsdl/st2071/2014/device/Device/OnlineResponse")
    public boolean getOnline();

    /**
     * 
     * @return
     *     returns org.smpte_ra.schemas.st2071._2014.types.Map
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/device/Device/Attributes")
    @WebResult(name = "Attributes", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/types")
    @RequestWrapper(localName = "getAttributes", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", className = "org.smpte_ra.schemas.st2071._2014.device.GetAttributes")
    @ResponseWrapper(localName = "getAttributesResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", className = "org.smpte_ra.schemas.st2071._2014.device.GetAttributesResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/device/Device/Attributes", output = "http://www.smpte-ra.org/wsdl/st2071/2014/device/Device/AttributesResponse")
    public Map getAttributes();

    /**
     * 
     * @return
     *     returns org.smpte_ra.schemas.st2071._2014.types.Capabilities
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/device/Device/Capabilities")
    @WebResult(name = "Capabilities", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/types")
    @RequestWrapper(localName = "getCapabilities", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", className = "org.smpte_ra.schemas.st2071._2014.device.GetCapabilities")
    @ResponseWrapper(localName = "getCapabilitiesResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", className = "org.smpte_ra.schemas.st2071._2014.device.GetCapabilitiesResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/device/Device/Capabilities", output = "http://www.smpte-ra.org/wsdl/st2071/2014/device/Device/CapabilitiesResponse")
    public Capabilities getCapabilities();

}
