package org.smpte_ra.schemas.st2071._2014.device;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * UCN = urn:smpte:ucn:org.smpte.st2071:device_directory_v1.0
 *         
 *
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-09T14:41:46.920-04:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", name = "DeviceDirectory")
@XmlSeeAlso({org.smpte_ra.schemas.st2071._2014.query.ObjectFactory.class, org.smpte_ra.schemas.st2071._2014.mode.ObjectFactory.class, org.smpte_ra.schemas.st2071._2014.media.ObjectFactory.class, org.smpte_ra.schemas.st2071._2014.types.ObjectFactory.class, org.smpte_ra.schemas.st2071._2014.security.ObjectFactory.class, org.smpte_ra.schemas.st2071._2014.identity.ObjectFactory.class, ObjectFactory.class, org.smpte_ra.schemas.st2071._2014.event.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DeviceDirectory {

    @WebResult(name = "childrenResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", partName = "childrenResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/device/DeviceDirectory/children", output = "http://www.smpte-ra.org/wsdl/st2071/2014/device/DeviceDirectory/childrenResponse", fault = {})
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/device/DeviceDirectory/children")
    public DeviceInformationsResponse children(
        @WebParam(partName = "children", name = "children", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device")
        UDNFilter children
    ) throws org.smpte_ra.schemas.st2071._2014.security.SecurityExceptionFault, DeviceNotFoundFault_Exception, org.smpte_ra.schemas.st2071._2014.query.InvalidQueryFault;

    @WebResult(name = "ancestorsResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", partName = "ancestorsResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/device/DeviceDirectory/ancestors", output = "http://www.smpte-ra.org/wsdl/st2071/2014/device/DeviceDirectory/ancestorsResponse", fault = {})
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/device/DeviceDirectory/ancestors")
    public DeviceInformationsResponse ancestors(
        @WebParam(partName = "ancestors", name = "ancestors", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device")
        Ancestors ancestors
    ) throws DeviceNotFoundFault_Exception, org.smpte_ra.schemas.st2071._2014.security.SecurityExceptionFault;

    @WebResult(name = "parentResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", partName = "parentResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/device/DeviceDirectory/parent", output = "http://www.smpte-ra.org/wsdl/st2071/2014/device/DeviceDirectory/parentResponse", fault = {})
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/device/DeviceDirectory/parent")
    public DeviceInformationResponse parent(
        @WebParam(partName = "parent", name = "parent", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device")
        Parent parent
    ) throws DeviceNotFoundFault_Exception, org.smpte_ra.schemas.st2071._2014.security.SecurityExceptionFault;

    @WebResult(name = "lookupResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", partName = "lookupResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/device/DeviceDirectory/lookup", output = "http://www.smpte-ra.org/wsdl/st2071/2014/device/DeviceDirectory/lookupResponse", fault = {})
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/device/DeviceDirectory/lookup")
    public DeviceInformationResponse lookup(
        @WebParam(partName = "lookup", name = "lookup", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device")
        Lookup lookup
    ) throws org.smpte_ra.schemas.st2071._2014.security.SecurityExceptionFault, DeviceNotFoundFault_Exception;

    @WebResult(name = "getNamespacesResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", partName = "getNamespacesResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/device/DeviceDirectory/Namespaces", output = "http://www.smpte-ra.org/wsdl/st2071/2014/device/DeviceDirectory/NamespacesResponse")
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/device/DeviceDirectory/Namespaces")
    public GetNamespacesResponse getNamespaces(
        @WebParam(partName = "getNamespaces", name = "getNamespaces", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device")
        GetNamespaces getNamespaces
    );

    @WebResult(name = "searchResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", partName = "searchResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/device/DeviceDirectory/search", output = "http://www.smpte-ra.org/wsdl/st2071/2014/device/DeviceDirectory/searchResponse", fault = {})
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/device/DeviceDirectory/search")
    public DeviceInformationsResponse search(
        @WebParam(partName = "search", name = "search", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device")
        UDNFilter search
    ) throws org.smpte_ra.schemas.st2071._2014.security.SecurityExceptionFault, DeviceNotFoundFault_Exception, org.smpte_ra.schemas.st2071._2014.query.InvalidQueryFault;

    @WebResult(name = "siblingsResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", partName = "siblingsResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/device/DeviceDirectory/siblings", output = "http://www.smpte-ra.org/wsdl/st2071/2014/device/DeviceDirectory/siblingsResponse", fault = {})
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/device/DeviceDirectory/siblings")
    public DeviceInformationsResponse siblings(
        @WebParam(partName = "siblings", name = "siblings", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device")
        UDNFilter siblings
    ) throws org.smpte_ra.schemas.st2071._2014.query.InvalidQueryFault, DeviceNotFoundFault_Exception, org.smpte_ra.schemas.st2071._2014.security.SecurityExceptionFault;

    @WebResult(name = "getParentDeviceDirectoryResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device", partName = "getParentDeviceDirectoryResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/device/DeviceDirectory/ParentDeviceDirectory", output = "http://www.smpte-ra.org/wsdl/st2071/2014/device/DeviceDirectory/ParentDeviceDirectoryResponse")
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/device/DeviceDirectory/ParentDeviceDirectory")
    public DeviceInformationResponse getParentDeviceDirectory(
        @WebParam(partName = "getParentDeviceDirectory", name = "getParentDeviceDirectory", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/device")
        GetParentDeviceDirectory getParentDeviceDirectory
    );
}
