
package org.smpte_ra.schemas.st2071._2014.media;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-09T14:41:59.641-04:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "MediaNotFound", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/media")
public class MediaNotFoundFault extends java.lang.Exception {
    
    private org.smpte_ra.schemas.st2071._2014.media.MediaNotFound mediaNotFound;

    public MediaNotFoundFault() {
        super();
    }
    
    public MediaNotFoundFault(String message) {
        super(message);
    }
    
    public MediaNotFoundFault(String message, Throwable cause) {
        super(message, cause);
    }

    public MediaNotFoundFault(String message, org.smpte_ra.schemas.st2071._2014.media.MediaNotFound mediaNotFound) {
        super(message);
        this.mediaNotFound = mediaNotFound;
    }

    public MediaNotFoundFault(String message, org.smpte_ra.schemas.st2071._2014.media.MediaNotFound mediaNotFound, Throwable cause) {
        super(message, cause);
        this.mediaNotFound = mediaNotFound;
    }

    public org.smpte_ra.schemas.st2071._2014.media.MediaNotFound getFaultInfo() {
        return this.mediaNotFound;
    }
}
