
package org.smpte_ra.schemas.st2071._2014.media;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.smpte_ra.schemas.st2071._2014.identity.URLs;


/**
 * 
 *             UCN = urn:smpte:ucn:org.smpte.st2071:media_access_v1.0
 *         
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MediaAccess", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/media")
@XmlSeeAlso({
    org.smpte_ra.schemas.st2071._2014.device.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.event.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.identity.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.media.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.mode.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.query.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.security.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.types.ObjectFactory.class
})
public interface MediaAccess {


    /**
     * 
     * @param umn
     * @return
     *     returns org.smpte_ra.schemas.st2071._2014.identity.URLs
     * @throws SecurityExceptionFault
     * @throws MediaNotFoundFault
     */
    @WebMethod(action = "http://www.smpte-ra.org/wsdl/st2071/2014/media/MediaAccess/lookupURLs")
    @WebResult(name = "URLs", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/identity")
    @RequestWrapper(localName = "lookupURLs", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/media", className = "org.smpte_ra.schemas.st2071._2014.media.UMNParameter")
    @ResponseWrapper(localName = "lookupURLsResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/media", className = "org.smpte_ra.schemas.st2071._2014.media.LookupURLsResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/media/MediaDirectory/lookupURLs", output = "http://www.smpte-ra.org/wsdl/st2071/2014/media/MediaDirectory/lookupURLsResponse")
    public URLs lookupURLs(
        @WebParam(name = "UMN", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/identity")
        String umn)
        throws MediaNotFoundFault, SecurityExceptionFault
    ;

}
