
package org.smpte_ra.schemas.st2071._2014.event;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * 
 *             The CallbackHandler Interface is a Client Side Interface Used to Receive Asynchronous Events
 *         
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CallbackHandler", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/event")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.smpte_ra.schemas.st2071._2014.event.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.identity.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.security.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.types.ObjectFactory.class
})
public interface CallbackHandler {


    /**
     * 
     * @param callback
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/event/CallbackHandler/callback")
    @Oneway
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/event/CallbackHandler/callback")
    public void callback(
        @WebParam(name = "callback", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/event", partName = "callback")
        Callback callback);

    /**
     * 
     * @param registered
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/event/CallbackHandler/registered")
    @Oneway
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/event/CallbackHandler/registered")
    public void registered(
        @WebParam(name = "registered", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/event", partName = "registered")
        URIParameter registered);

    /**
     * 
     * @param unregistered
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/event/CallbackHandler/unregistered")
    @Oneway
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/event/CallbackHandler/unregistered")
    public void unregistered(
        @WebParam(name = "unregistered", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/event", partName = "unregistered")
        URIParameter unregistered);

}
