
package org.smpte_ra.schemas.st2071._2014.event;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * 
 *             UCN = urn:smpte:ucn:org.smpte.st2071:event_broadcaster_v1.0
 *         
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EventBroadcaster", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/event")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.smpte_ra.schemas.st2071._2014.event.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.identity.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.security.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.types.ObjectFactory.class
})
public interface EventBroadcaster {


    /**
     * 
     * @param registerCallback
     * @return
     *     returns org.smpte_ra.schemas.st2071._2014.event.RegisterCallbackResponse
     * @throws SecurityExceptionFault
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/eventBroadcaster/registerCallback")
    @WebResult(name = "registerCallbackResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/event", partName = "registerCallbackResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/event/EventBroadcaster/registerCallback", output = "http://www.smpte-ra.org/wsdl/st2071/2014/event/EventBroadcaster/registerCallbackResponse")
    public RegisterCallbackResponse registerCallback(
        @WebParam(name = "registerCallback", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/event", partName = "registerCallback")
        URIParameter registerCallback)
        throws SecurityExceptionFault
    ;

    /**
     * 
     * @param unregisterCallback
     * @return
     *     returns org.smpte_ra.schemas.st2071._2014.event.UnregisterCallbackResponse
     * @throws SecurityExceptionFault
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/eventBroadcaster/unregisterCallback")
    @WebResult(name = "unregisterCallbackResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/event", partName = "unregisterCallbackResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/event/EventBroadcaster/unregisterCallback", output = "http://www.smpte-ra.org/wsdl/st2071/2014/event/EventBroadcaster/unregisterCallbackResponse")
    public UnregisterCallbackResponse unregisterCallback(
        @WebParam(name = "unregisterCallback", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/event", partName = "unregisterCallback")
        URIParameter unregisterCallback)
        throws SecurityExceptionFault
    ;

}
