
package org.smpte_ra.schemas.st2071._2014.event;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * 
 *             UCN = urn:smpte:ucn:org.smpte.st2071:status_support_v1.0
 *         
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StatusSupport", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/event")
@XmlSeeAlso({
    org.smpte_ra.schemas.st2071._2014.event.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.identity.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.security.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.types.ObjectFactory.class
})
public interface StatusSupport {


    /**
     * 
     * @return
     *     returns org.smpte_ra.schemas.st2071._2014.event.StatusEvent
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/event/StatusSupport/Status")
    @WebResult(name = "StatusEvent", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/event")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/event", className = "org.smpte_ra.schemas.st2071._2014.event.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/event", className = "org.smpte_ra.schemas.st2071._2014.event.GetStatusResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/event/StatusSupport/Status", output = "http://www.smpte-ra.org/wsdl/st2071/2014/event/StatusSupport/StatusResponse")
    public StatusEvent getStatus();

}
