package org.smpte_ra.schemas.st2071._2014.event;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * UCN = urn:smpte:ucn:org.smpte.st2071:status_support_v1.0
 *         
 *
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-09T14:41:23.010-04:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/event", name = "StatusSupport")
@XmlSeeAlso({org.smpte_ra.schemas.st2071._2014.types.ObjectFactory.class, org.smpte_ra.schemas.st2071._2014.security.ObjectFactory.class, org.smpte_ra.schemas.st2071._2014.identity.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StatusSupport {

    @WebResult(name = "getStatusResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/event", partName = "getStatusResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/event/StatusSupport/Status", output = "http://www.smpte-ra.org/wsdl/st2071/2014/event/StatusSupport/StatusResponse")
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/event/StatusSupport/Status")
    public GetStatusResponse getStatus(
        @WebParam(partName = "getStatus", name = "getStatus", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/event")
        GetStatus getStatus
    );
}
