// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 1.1.4322.2032
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Mono Web Services Description Language Utility
//


/// <remarks/>
[System.Web.Services.WebServiceBinding(Name="ModeSupportPort", Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public class DeviceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    public DeviceService() {
        this.Url = "http://localhost:8088/ModeSupport";
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/mode/ModeSupport/Modes", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("getModesResponse", Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")]
    public getModesResponse getModes([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")] getModes getModes) {
        object[] results = this.Invoke("getModes", new object[] {
                    getModes});
        return ((getModesResponse)(results[0]));
    }
    
    public System.IAsyncResult BegingetModes(getModes getModes, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getModes", new object[] {
                    getModes}, callback, asyncState);
    }
    
    public getModesResponse EndgetModes(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((getModesResponse)(results[0]));
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/mode/ModeSupport/ActiveMode", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("getActiveModeResponse", Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")]
    public getActiveModeResponse getActiveMode([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")] getActiveMode getActiveMode) {
        object[] results = this.Invoke("getActiveMode", new object[] {
                    getActiveMode});
        return ((getActiveModeResponse)(results[0]));
    }
    
    public System.IAsyncResult BegingetActiveMode(getActiveMode getActiveMode, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getActiveMode", new object[] {
                    getActiveMode}, callback, asyncState);
    }
    
    public getActiveModeResponse EndgetActiveMode(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((getActiveModeResponse)(results[0]));
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/mode/ModeSupport/changeMode", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("changeModeResponse", Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")]
    public changeModeResponse changeMode([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")] changeMode changeMode) {
        object[] results = this.Invoke("changeMode", new object[] {
                    changeMode});
        return ((changeModeResponse)(results[0]));
    }
    
    public System.IAsyncResult BeginchangeMode(changeMode changeMode, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("changeMode", new object[] {
                    changeMode}, callback, asyncState);
    }
    
    public changeModeResponse EndchangeMode(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((changeModeResponse)(results[0]));
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")]
public class getModes {
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")]
public class getModesResponse {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public Mode[] Modes;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")]
public class Mode {
    
    /// <remarks/>
    public string Name;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArray(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/types")]
    [System.Xml.Serialization.XmlArrayItem(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable=false)]
    public Capability[] Capabilities;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/types")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/types")]
public class Capability {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType="anyURI")]
    public string UCN;
    
    /// <remarks/>
    public Map Attributes;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArray(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/identity")]
    [System.Xml.Serialization.XmlArrayItem(ElementName="URL", Namespace="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable=false)]
    public string[] URLs;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/types")]
[System.Xml.Serialization.XmlRootAttribute("Attributes", Namespace="http://www.smpte-ra.org/schemas/st2071/2014/types")]
public class Map {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public MapEntry[] Entries;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/types")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/types")]
public class MapEntry {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public string key;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public DATA_TYPE type;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/types")]
public enum DATA_TYPE {
    
    /// <remarks/>
    BOOLEAN,
    
    /// <remarks/>
    STRING,
    
    /// <remarks/>
    INTEGER,
    
    /// <remarks/>
    FLOAT,
    
    /// <remarks/>
    DATETIME,
    
    /// <remarks/>
    URI,
    
    /// <remarks/>
    MAP,
    
    /// <remarks/>
    BLOB,
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")]
public class getActiveMode {
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")]
public class getActiveModeResponse {
    
    /// <remarks/>
    public Mode Mode;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")]
public class changeMode {
    
    /// <remarks/>
    public Mode Mode;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.smpte-ra.org/schemas/st2071/2014/mode")]
public class changeModeResponse {
}
