'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Mono Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Explicit On
Option Strict On


'
' This source code was auto-generated by Mono Web Services Description Language Utility
'
'WARNING: Could not generate operation binding list. The XML element named 'RN' from namespace 'http://www.smpte-ra.org/schemas/st2071/2014/identity' is already present in the current scope. Use XML attributes to specify another XML name or namespace for the element.

'''<remarks/>
<System.Web.Services.WebServiceBinding(Name:="MediaDirectoryPort", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getParentDeviceDirectory)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(LESS_THAN)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(setOnlineResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(lookup)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(URIParameter)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(CONTAINS)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(UDNFilter)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getMechanisms)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getActiveMode)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceNotFoundFault)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(changeModeResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(authorizeResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getUDN)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getActiveModeResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(authenticateResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getOnlineResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(Role)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getURLsResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getStatus)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(Image)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(setOnline)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(pollResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType([IMPLEMENTS])),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(Permission)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getCapabilities)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getStatusResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getNamespaces)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(unbind)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MATCHES)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(registerCallbackResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getCapabilitiesResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(authenticate)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(bind)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getName)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getAttributes)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(Exception)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(lookupURLsResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(changeMode)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getOnline)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(callback)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(bindResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getAttributesResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaInstance)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(GREATER_THAN)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getMechanismsResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceInformationResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(heartbeatResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(parent)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(UDNParameter)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getURLs)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getModesResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(logout)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceInformationsResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceException)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(unregisterCallbackResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getUDNResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(ancestors)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getNameResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getModes)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaFile)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(logoutResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(authorize)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getNamespacesResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(unbindResponse))>  _
Public Class MediaDirectoryHTTPBinding
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Public Sub New()
        MyBase.New
        Me.Url = "http://localhost:8088/MediaDirectory"
    End Sub
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/media/MediaDirectory/MediaContainer", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function getMediaContainer(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")> ByVal getMediaContainer As getMediaContainer) As <System.Xml.Serialization.XmlElementAttribute("getMediaContainerResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")> getMediaContainerResponse
        Dim results As Object() = Me.Invoke("getMediaContainer", New Object() {getMediaContainer})
        Return CType(results(0), getMediaContainerResponse)
    End Function
    
    Public Function BegingetMediaContainer(ByVal getMediaContainer As getMediaContainer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getMediaContainer", New Object() {getMediaContainer}, callback, asyncState)
    End Function
    
    Public Function EndgetMediaContainer(ByVal asyncResult As System.IAsyncResult) As getMediaContainerResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), getMediaContainerResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/media/MediaDirectory/create", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function create(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")> ByVal create As create) As <System.Xml.Serialization.XmlElementAttribute("createResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")> MediaResponse
        Dim results As Object() = Me.Invoke("create", New Object() {create})
        Return CType(results(0), MediaResponse)
    End Function
    
    Public Function Begincreate(ByVal create As create, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("create", New Object() {create}, callback, asyncState)
    End Function
    
    Public Function Endcreate(ByVal asyncResult As System.IAsyncResult) As MediaResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), MediaResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/media/MediaDirectory/delete", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function delete(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")> ByVal delete As UMNParameter) As <System.Xml.Serialization.XmlElementAttribute("deleteResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")> MediaResponse
        Dim results As Object() = Me.Invoke("delete", New Object() {delete})
        Return CType(results(0), MediaResponse)
    End Function
    
    Public Function Begindelete(ByVal delete As UMNParameter, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("delete", New Object() {delete}, callback, asyncState)
    End Function
    
    Public Function Enddelete(ByVal asyncResult As System.IAsyncResult) As MediaResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), MediaResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/media/MediaDirectory/lookup", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function lookup(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")> ByVal lookup As UMNParameter) As <System.Xml.Serialization.XmlElementAttribute("lookupResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")> MediaResponse
        Dim results As Object() = Me.Invoke("lookup", New Object() {lookup})
        Return CType(results(0), MediaResponse)
    End Function
    
    Public Function Beginlookup(ByVal lookup As UMNParameter, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("lookup", New Object() {lookup}, callback, asyncState)
    End Function
    
    Public Function Endlookup(ByVal asyncResult As System.IAsyncResult) As MediaResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), MediaResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/media/MediaDirectory/lookupAsset", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function lookupAsset(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")> ByVal lookupAsset As UMNParameter) As <System.Xml.Serialization.XmlElementAttribute("lookupAssetResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")> lookupAssetResponse
        Dim results As Object() = Me.Invoke("lookupAsset", New Object() {lookupAsset})
        Return CType(results(0), lookupAssetResponse)
    End Function
    
    Public Function BeginlookupAsset(ByVal lookupAsset As UMNParameter, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("lookupAsset", New Object() {lookupAsset}, callback, asyncState)
    End Function
    
    Public Function EndlookupAsset(ByVal asyncResult As System.IAsyncResult) As lookupAssetResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), lookupAssetResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/media/MediaDirectory/search", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function search(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")> ByVal search As UMNFilter) As <System.Xml.Serialization.XmlElementAttribute("searchResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")> MediaListResponse
        Dim results As Object() = Me.Invoke("search", New Object() {search})
        Return CType(results(0), MediaListResponse)
    End Function
    
    Public Function Beginsearch(ByVal search As UMNFilter, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("search", New Object() {search}, callback, asyncState)
    End Function
    
    Public Function Endsearch(ByVal asyncResult As System.IAsyncResult) As MediaListResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), MediaListResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/media/MediaDirectory/update", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function update(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")> ByVal update As update) As <System.Xml.Serialization.XmlElementAttribute("updateResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")> MediaResponse
        Dim results As Object() = Me.Invoke("update", New Object() {update})
        Return CType(results(0), MediaResponse)
    End Function
    
    Public Function Beginupdate(ByVal update As update, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("update", New Object() {update}, callback, asyncState)
    End Function
    
    Public Function Endupdate(ByVal asyncResult As System.IAsyncResult) As MediaResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), MediaResponse)
    End Function
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class getMediaContainer
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class getMediaContainerResponse
    
    '''<remarks/>
    Public MediaContainer As MediaContainer
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaContainer
    Inherits Media
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaContainer)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaSegment)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaAsset)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MaterialAsset)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaFile)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaInstance)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaBundle))>  _
Public Class Media
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UMN As String
    
    '''<remarks/>
    Public Name As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public Location As String
    
    '''<remarks/>
    Public Created As DateTime
    
    '''<remarks/>
    Public Modified As DateTime
    
    '''<remarks/>
    Public Metadata As Map
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlRootAttribute("ValidTill", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(FramedTime))>  _
Public Class DateTime
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Value As Date
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
Public Class FramedTime
    Inherits DateTime
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="", DataType:="nonNegativeInteger")>  _
    Public frame As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="", DataType:="nonNegativeInteger")>  _
    Public frame_rate As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="", DataType:="nonNegativeInteger")>  _
    Public scale As String
    
    '''<remarks/>
    <System.ComponentModel.DefaultValue("0"),  _
     System.Xml.Serialization.XmlAttributeAttribute(Namespace:="", DataType:="nonNegativeInteger")>  _
    Public total_frames As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlRootAttribute("Attributes", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
Public Class Map
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Entries As MapEntry()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
Public Class MapEntry
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public key As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public type As DATA_TYPE
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Value As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
Public Enum DATA_TYPE
    
    '''<remarks/>
    BOOLEAN
    
    '''<remarks/>
    STRING
    
    '''<remarks/>
    INTEGER
    
    '''<remarks/>
    FLOAT
    
    '''<remarks/>
    DATETIME
    
    '''<remarks/>
    URI
    
    '''<remarks/>
    MAP
    
    '''<remarks/>
    BLOB
End Enum

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaSegment
    Inherits Media
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public Source As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>  _
    Public InpointOffset As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>  _
    Public OutpointOffset As String
    
    '''<remarks/>
    Public OffsetType As OFFSET_TYPE
    
    '''<remarks/>
    Public Track As System.UInt16
    
    '''<remarks/>
    Public Inpoint As DateTime
    
    '''<remarks/>
    Public Outpoint As DateTime
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public Format As String
    
    '''<remarks/>
    Public TrackName As String
    
    '''<remarks/>
    Public TrackType As TRACK_TYPE
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlRootAttribute("OffsetType", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Enum OFFSET_TYPE
    
    '''<remarks/>
    SECOND
    
    '''<remarks/>
    MICROSECOND
    
    '''<remarks/>
    BYTE
    
    '''<remarks/>
    FRAME
End Enum

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute("TrackType", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Enum TRACK_TYPE
    
    '''<remarks/>
    AUDIO
    
    '''<remarks/>
    VIDEO
    
    '''<remarks/>
    TIMECODE
    
    '''<remarks/>
    TEXT
    
    '''<remarks/>
    DATA
End Enum

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MaterialAsset))>  _
Public Class MediaAsset
    Inherits Media
    
    '''<remarks/>
    Public Duration As DateTime
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Composition As MediaSegment()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MaterialAsset
    Inherits MediaAsset
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaInstance)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaBundle))>  _
Public Class MediaFile
    Inherits Media
    
    '''<remarks/>
    Public MIMEType As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>  _
    Public Size As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaBundle))>  _
Public Class MediaInstance
    Inherits MediaFile
    
    '''<remarks/>
    Public Duration As FramedTime
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Composition As MediaSegment()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaBundle
    Inherits MediaInstance
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class create
    
    '''<remarks/>
    Public Media As Media
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("MediaPointer")>  _
    Public MediaPointer As MediaPointer()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaPointer
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public Source As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>  _
    Public InpointOffset As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>  _
    Public OutpointOffset As String
    
    '''<remarks/>
    Public OffsetType As OFFSET_TYPE
    
    '''<remarks/>
    Public Track As System.UInt16
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute("updateResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaResponse
    
    '''<remarks/>
    Public Media As Media
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute("lookupURLs", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class UMNParameter
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UMN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class lookupAssetResponse
    
    '''<remarks/>
    Public MediaAsset As MediaAsset
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute("search", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class UMNFilter
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UMN As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
    Public QueryExpression As QueryExpression
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class QueryExpression
    
    '''<remarks/>
    Public Expression As Expression
    
    '''<remarks/>
    Public PAGE As PAGE
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("SORT_BY")>  _
    Public SORT_BY As SORT_BY()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType([NOT])),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType([AND])),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType([OR])),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(EQUALS)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(GREATER_THAN)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(LESS_THAN)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MATCHES)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(CONTAINS)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType([IMPLEMENTS]))>  _
Public Class Expression
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class [NOT]
    Inherits Expression
    
    '''<remarks/>
    Public Expression As Expression
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class [AND]
    Inherits Expression
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Expression")>  _
    Public Expression As Expression()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class [OR]
    Inherits Expression
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Expression")>  _
    Public Expression As Expression()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class EQUALS
    Inherits Expression
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public field As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Object"),  _
     System.Xml.Serialization.XmlElementAttribute("Time", Type:=GetType(DateTime)),  _
     System.Xml.Serialization.XmlElementAttribute("Number", Type:=GetType(Decimal))>  _
    Public Item As Object
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class PAGE
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="", DataType:="positiveInteger")>  _
    Public page_size As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="", DataType:="positiveInteger")>  _
    Public offset As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class SORT_BY
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public field As String
    
    '''<remarks/>
    <System.ComponentModel.DefaultValue(false),  _
     System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public descending As Boolean
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class GREATER_THAN
    Inherits Expression
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public field As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Object"),  _
     System.Xml.Serialization.XmlElementAttribute("Time", Type:=GetType(DateTime)),  _
     System.Xml.Serialization.XmlElementAttribute("Number", Type:=GetType(Decimal))>  _
    Public Item As Object
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class LESS_THAN
    Inherits Expression
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public field As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Object"),  _
     System.Xml.Serialization.XmlElementAttribute("Time", Type:=GetType(DateTime)),  _
     System.Xml.Serialization.XmlElementAttribute("Number", Type:=GetType(Decimal))>  _
    Public Item As Object
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class MATCHES
    Inherits Expression
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public field As String
    
    '''<remarks/>
    Public RegExp As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class CONTAINS
    Inherits Expression
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
    Public MediaPointer As MediaPointer
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class [IMPLEMENTS]
    Inherits Expression
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
    Public Mode As Mode
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable:=false)>  _
    Public Interfaces As Capability()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class Mode
    
    '''<remarks/>
    Public Name As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
     System.Xml.Serialization.XmlArrayItem(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable:=false)>  _
    Public Capabilities As Capability()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
Public Class Capability
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UCN As String
    
    '''<remarks/>
    Public Attributes As Map
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity"),  _
     System.Xml.Serialization.XmlArrayItem(ElementName:="UCN", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public URLs As String()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaNotFound)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaCreationFailed)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaDeletionFailed)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaUpdateFailed)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(InvalidQuery)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(InvalidMode)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(ModeException)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceException)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceNotFound)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceNotBound)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceNotUnbound)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceAlreadyBound)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(SecurityException))>  _
Public Class Exception
    
    '''<remarks/>
    Public Message As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaNotFound
    Inherits Exception
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UMN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaCreationFailed
    Inherits Exception
    
    '''<remarks/>
    Public Media As Media
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaDeletionFailed
    Inherits Exception
    
    '''<remarks/>
    Public Media As Media
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaUpdateFailed
    Inherits Exception
    
    '''<remarks/>
    Public Media As Media
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class InvalidQuery
    Inherits Exception
    
    '''<remarks/>
    Public QueryExpression As QueryExpression
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class InvalidMode
    Inherits Exception
    
    '''<remarks/>
    Public Mode As Mode
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class ModeException
    Inherits Exception
    
    '''<remarks/>
    Public Mode As Mode
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceNotFound)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceNotBound)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceNotUnbound)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceAlreadyBound))>  _
Public Class DeviceException
    Inherits Exception
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class DeviceNotFound
    Inherits DeviceException
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class DeviceNotBound
    Inherits DeviceException
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public ParentUDN As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity"),  _
     System.Xml.Serialization.XmlArrayItem(ElementName:="UCN", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public URLs As String()
    
    '''<remarks/>
    Public Name As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
     System.Xml.Serialization.XmlArrayItem(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable:=false)>  _
    Public Capabilities As Capability()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class DeviceNotUnbound
    Inherits DeviceException
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public ParentUDN As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity"),  _
     System.Xml.Serialization.XmlArrayItem(ElementName:="UCN", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public URLs As String()
    
    '''<remarks/>
    Public Name As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
     System.Xml.Serialization.XmlArrayItem(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable:=false)>  _
    Public Capabilities As Capability()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class DeviceAlreadyBound
    Inherits DeviceException
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class SecurityException
    Inherits Exception
    
    '''<remarks/>
    Public Type As EXCEPTION_TYPE
    
    '''<remarks/>
    Public Status As EXCEPTION_STATUS
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public Resource As String
    
    '''<remarks/>
    Public Subject As Subject
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security"),  _
 System.Xml.Serialization.XmlRootAttribute("Type", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Enum EXCEPTION_TYPE
    
    '''<remarks/>
    AUTHENTICATION
    
    '''<remarks/>
    AUTHORIZATION
    
    '''<remarks/>
    SECURITY_LAYER
End Enum

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security"),  _
 System.Xml.Serialization.XmlRootAttribute("Status", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Enum EXCEPTION_STATUS
    
    '''<remarks/>
    REQUIRED
    
    '''<remarks/>
    FAILED
    
    '''<remarks/>
    ABORTED
    
    '''<remarks/>
    ERROR
    
    '''<remarks/>
    EXPIRED
End Enum

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class Subject
    
    '''<remarks/>
    Public Name As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Principals As Principal()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class Principal
    
    '''<remarks/>
    Public Realm As String
    
    '''<remarks/>
    Public Identifier As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Roles As Principal()
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Tokens As SecurityToken()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class SecurityToken
    
    '''<remarks/>
    Public Mechanism As String
    
    '''<remarks/>
    Public Data As Byte()
    
    '''<remarks/>
    Public ValidTill As DateTime
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(StatusEvent)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaEvent)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(ModeEvent)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceEvent))>  _
Public Class [Event]
    
    '''<remarks/>
    Public Type As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public RN As String
    
    '''<remarks/>
    Public EventTime As DateTime
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaEvent)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(ModeEvent)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceEvent))>  _
Public Class StatusEvent
    Inherits [Event]
    
    '''<remarks/>
    Public Ready As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public STATUS As STATUS
    
    '''<remarks/>
    Public Message As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
Public Enum STATUS
    
    '''<remarks/>
    OK
    
    '''<remarks/>
    WARNING
    
    '''<remarks/>
    ERROR
End Enum

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaEvent
    Inherits StatusEvent
    
    '''<remarks/>
    Public Media As Media
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class ModeEvent
    Inherits StatusEvent
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class DeviceEvent
    Inherits StatusEvent
    
    '''<remarks/>
    Public Device As DeviceInformation
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class DeviceInformation
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity"),  _
     System.Xml.Serialization.XmlArrayItem(ElementName:="UCN", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public URLs As String()
    
    '''<remarks/>
    Public Name As String
    
    '''<remarks/>
    Public Online As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public Attributes As Map
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
     System.Xml.Serialization.XmlArrayItem(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable:=false)>  _
    Public Capabilities As Capability()
    
    '''<remarks/>
    Public ValidTill As DateTime
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute("searchResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaListResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public MediaList As Media()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class update
    
    '''<remarks/>
    Public Media As Media
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class lookupURLsResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity"),  _
     System.Xml.Serialization.XmlArrayItem(ElementName:="UCN", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public URLs As String()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
Public Class Image
    
    '''<remarks/>
    Public MIMEType As String
    
    '''<remarks/>
    Public Height As System.UInt16
    
    '''<remarks/>
    Public Width As System.UInt16
    
    '''<remarks/>
    Public Data As Byte()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class getModes
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class getModesResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Modes As Mode()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class getActiveMode
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class getActiveModeResponse
    
    '''<remarks/>
    Public Mode As Mode
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class changeMode
    
    '''<remarks/>
    Public Mode As Mode
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class changeModeResponse
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class getStatus
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class getStatusResponse
    
    '''<remarks/>
    Public StatusEvent As StatusEvent
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class URIParameter
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public URI As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class UDNParameter
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class pollResponse
    
    '''<remarks/>
    Public [Event] As [Event]
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class registerCallbackResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public [Boolean] As Boolean
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class unregisterCallbackResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public [Boolean] As Boolean
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class callback
    
    '''<remarks/>
    Public [Event] As [Event]
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class heartbeatResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public [Boolean] As Boolean
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getUDN
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getURLs
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getName
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getOnline
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getAttributes
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getCapabilities
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getParentDeviceDirectory
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getNamespaces
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class ancestors
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class lookup
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class parent
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class UDNFilter
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
    Public QueryExpression As QueryExpression
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class bind
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public UDN As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public ParentUDN As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(ElementName:="UCN", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public URLs As String()
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
     System.Xml.Serialization.XmlArrayItem(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable:=false)>  _
    Public Capabilities As Capability()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class unbind
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class setOnline
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public [Boolean] As Boolean
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getUDNResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getURLsResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity"),  _
     System.Xml.Serialization.XmlArrayItem(ElementName:="UCN", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public URLs As String()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getNameResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public [String] As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getOnlineResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public [Boolean] As Boolean
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getAttributesResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public Attributes As Map
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getCapabilitiesResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
     System.Xml.Serialization.XmlArrayItem(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable:=false)>  _
    Public Capabilities As Capability()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getNamespacesResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity"),  _
     System.Xml.Serialization.XmlArrayItem(ElementName:="UCN", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public UDNs As String()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class DeviceInformationsResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public DeviceInformations As DeviceInformation()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class DeviceInformationResponse
    
    '''<remarks/>
    Public DeviceInformation As DeviceInformation
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class bindResponse
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class unbindResponse
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class setOnlineResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public [Boolean] As Boolean
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class DeviceNotFoundFault
    
    '''<remarks/>
    Public DeviceNotFound As DeviceNotFound
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security"),  _
 System.Xml.Serialization.XmlRootAttribute("Parent", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class Role
    
    '''<remarks/>
    Public Parent As Role
    
    '''<remarks/>
    Public Name As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class Permission
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Roles As Principal()
    
    '''<remarks/>
    Public Allow As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Permissions As PERMISSION_TYPE()
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public Resource As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Enum PERMISSION_TYPE
    
    '''<remarks/>
    READ
    
    '''<remarks/>
    WRITE
    
    '''<remarks/>
    EXECUTE
    
    '''<remarks/>
    DELETE
    
    '''<remarks/>
    ADMINISTER
End Enum

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class getMechanisms
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class getMechanismsResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(ElementName:="Mechanism", IsNullable:=false)>  _
    Public Mechanisms As String()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class authorize
    
    '''<remarks/>
    Public Subject As Subject
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public URI As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class authorizeResponse
    
    '''<remarks/>
    Public Subject As Subject
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class authenticate
    
    '''<remarks/>
    Public Subject As Subject
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class authenticateResponse
    
    '''<remarks/>
    Public Subject As Subject
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class logout
    
    '''<remarks/>
    Public Subject As Subject
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class logoutResponse
    
    '''<remarks/>
    Public Subject As Subject
End Class

'''<remarks/>
<System.Web.Services.WebServiceBinding(Name:="MediaAccessPort", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getParentDeviceDirectory)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(LESS_THAN)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(setOnlineResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(lookup)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(URIParameter)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(CONTAINS)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(UDNFilter)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getMechanisms)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getActiveMode)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceNotFoundFault)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(changeModeResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(authorizeResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getUDN)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getActiveModeResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(authenticateResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getOnlineResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(Role)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getURLsResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getStatus)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(Image)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(setOnline)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(pollResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType([IMPLEMENTS])),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(Permission)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getCapabilities)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getStatusResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getNamespaces)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(unbind)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MATCHES)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(registerCallbackResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getCapabilitiesResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(authenticate)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(bind)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getName)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getAttributes)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(Exception)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(lookupURLsResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(changeMode)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getOnline)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(callback)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(bindResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getAttributesResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaInstance)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(GREATER_THAN)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getMechanismsResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceInformationResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(heartbeatResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(parent)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(UDNParameter)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getURLs)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getModesResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(logout)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceInformationsResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceException)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(unregisterCallbackResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getUDNResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(ancestors)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getNameResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getModes)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaFile)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(logoutResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(authorize)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(getNamespacesResponse)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(unbindResponse))>  _
Public Class MediaAccessHTTPBinding
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Public Sub New()
        MyBase.New
        Me.Url = "http://localhost:8088/MediaAccess"
    End Sub
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/media/MediaAccess/lookupURLs", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function lookupURLs(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")> ByVal lookupURLs As UMNParameter) As <System.Xml.Serialization.XmlElementAttribute("lookupURLsResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")> lookupURLsResponse
        Dim results As Object() = Me.Invoke("lookupURLs", New Object() {lookupURLs})
        Return CType(results(0), lookupURLsResponse)
    End Function
    
    Public Function BeginlookupURLs(ByVal lookupURLs As UMNParameter, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("lookupURLs", New Object() {lookupURLs}, callback, asyncState)
    End Function
    
    Public Function EndlookupURLs(ByVal asyncResult As System.IAsyncResult) As lookupURLsResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), lookupURLsResponse)
    End Function
End Class
