'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Mono Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Explicit On
Option Strict On


'
' This source code was auto-generated by Mono Web Services Description Language Utility
'
'WARNING: Could not generate operation binding search. The XML element named 'RN' from namespace 'http://www.smpte-ra.org/schemas/st2071/2014/identity' is already present in the current scope. Use XML attributes to specify another XML name or namespace for the element.

'''<remarks/>
<System.Web.Services.WebServiceBinding(Name:="ServicePort", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Public Class ServiceHTTPBinding
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Public Sub New()
        MyBase.New
        Me.Url = "http://localhost:8088/Service"
    End Sub
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/schemas/st2071/2014/service/Service/USN", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function getUSN(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> ByVal getUSN As getUSN) As <System.Xml.Serialization.XmlElementAttribute("getUSNResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> getUSNResponse
        Dim results As Object() = Me.Invoke("getUSN", New Object() {getUSN})
        Return CType(results(0), getUSNResponse)
    End Function
    
    Public Function BegingetUSN(ByVal getUSN As getUSN, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getUSN", New Object() {getUSN}, callback, asyncState)
    End Function
    
    Public Function EndgetUSN(ByVal asyncResult As System.IAsyncResult) As getUSNResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), getUSNResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/schemas/st2071/2014/service/Service/Type", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function getType(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> ByVal [getType] As [getType]) As <System.Xml.Serialization.XmlElementAttribute("getTypeResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> getTypeResponse
        Dim results As Object() = Me.Invoke("getType", New Object() {[getType]})
        Return CType(results(0), getTypeResponse)
    End Function
    
    Public Function BegingetType(ByVal [getType] As [getType], ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getType", New Object() {[getType]}, callback, asyncState)
    End Function
    
    Public Function EndgetType(ByVal asyncResult As System.IAsyncResult) As getTypeResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), getTypeResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/schemas/st2071/2014/service/Service/State", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function getState(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> ByVal getState As getState) As <System.Xml.Serialization.XmlElementAttribute("getStateResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> getStateResponse
        Dim results As Object() = Me.Invoke("getState", New Object() {getState})
        Return CType(results(0), getStateResponse)
    End Function
    
    Public Function BegingetState(ByVal getState As getState, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getState", New Object() {getState}, callback, asyncState)
    End Function
    
    Public Function EndgetState(ByVal asyncResult As System.IAsyncResult) As getStateResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), getStateResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/schemas/st2071/2014/service/Service/URLs", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function getURLs(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> ByVal getURLs As getURLs) As <System.Xml.Serialization.XmlElementAttribute("getURLsResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> getURLsResponse
        Dim results As Object() = Me.Invoke("getURLs", New Object() {getURLs})
        Return CType(results(0), getURLsResponse)
    End Function
    
    Public Function BegingetURLs(ByVal getURLs As getURLs, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getURLs", New Object() {getURLs}, callback, asyncState)
    End Function
    
    Public Function EndgetURLs(ByVal asyncResult As System.IAsyncResult) As getURLsResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), getURLsResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/service/Service/Attributes", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function getAttributes(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> ByVal getAttributes As getAttributes) As <System.Xml.Serialization.XmlElementAttribute("getAttributesResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> getAttributesResponse
        Dim results As Object() = Me.Invoke("getAttributes", New Object() {getAttributes})
        Return CType(results(0), getAttributesResponse)
    End Function
    
    Public Function BegingetAttributes(ByVal getAttributes As getAttributes, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getAttributes", New Object() {getAttributes}, callback, asyncState)
    End Function
    
    Public Function EndgetAttributes(ByVal asyncResult As System.IAsyncResult) As getAttributesResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), getAttributesResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/service/Service/Capabilities", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function getCapabilities(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> ByVal getCapabilities As getCapabilities) As <System.Xml.Serialization.XmlElementAttribute("getCapabilitiesResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> getCapabilitiesResponse
        Dim results As Object() = Me.Invoke("getCapabilities", New Object() {getCapabilities})
        Return CType(results(0), getCapabilitiesResponse)
    End Function
    
    Public Function BegingetCapabilities(ByVal getCapabilities As getCapabilities, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getCapabilities", New Object() {getCapabilities}, callback, asyncState)
    End Function
    
    Public Function EndgetCapabilities(ByVal asyncResult As System.IAsyncResult) As getCapabilitiesResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), getCapabilitiesResponse)
    End Function
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class getUSN
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class getUSNResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public USN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class [getType]
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class getTypeResponse
    
    '''<remarks/>
    Public ServiceTemplate As ServiceTemplate
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class ServiceTemplate
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public USN As String
    
    '''<remarks/>
    Public Attributes As Map
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
     System.Xml.Serialization.XmlArrayItem(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable:=false)>  _
    Public Capabilities As Capability()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlRootAttribute("Metadata", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class Map
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Entries As MapEntry()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
Public Class MapEntry
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public key As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public type As DATA_TYPE
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Value As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
Public Enum DATA_TYPE
    
    '''<remarks/>
    BOOLEAN
    
    '''<remarks/>
    STRING
    
    '''<remarks/>
    INTEGER
    
    '''<remarks/>
    FLOAT
    
    '''<remarks/>
    DATETIME
    
    '''<remarks/>
    URI
    
    '''<remarks/>
    MAP
    
    '''<remarks/>
    BLOB
End Enum

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
Public Class Capability
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UCN As String
    
    '''<remarks/>
    Public Attributes As Map
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity"),  _
     System.Xml.Serialization.XmlArrayItem(ElementName:="URL", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public URLs As String()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class getState
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class getStateResponse
    
    '''<remarks/>
    Public State As SERVICE_STATE
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute("State", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Enum SERVICE_STATE
    
    '''<remarks/>
    STARTING
    
    '''<remarks/>
    STARTED
    
    '''<remarks/>
    STOPPING
    
    '''<remarks/>
    STOPPED
End Enum

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class getURLs
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class getURLsResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity"),  _
     System.Xml.Serialization.XmlArrayItem(ElementName:="URL", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public URLs As String()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class getAttributes
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class getAttributesResponse
    
    '''<remarks/>
    Public Attributes As Map
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class getCapabilities
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class getCapabilitiesResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
     System.Xml.Serialization.XmlArrayItem(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable:=false)>  _
    Public Capabilities As Capability()
End Class

'''<remarks/>
<System.Web.Services.WebServiceBinding(Name:="ServiceDirectoryPort", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Public Class ServiceDirectoryHTTPBinding
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Public Sub New()
        MyBase.New
        Me.Url = "http://localhost:8088/ServiceDirectory"
    End Sub
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/service/ServiceDirectory/Namespaces", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function getNamespaces(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> ByVal getNamespaces As getNamespaces) As <System.Xml.Serialization.XmlElementAttribute("getNamespacesResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> getNamespacesResponse
        Dim results As Object() = Me.Invoke("getNamespaces", New Object() {getNamespaces})
        Return CType(results(0), getNamespacesResponse)
    End Function
    
    Public Function BegingetNamespaces(ByVal getNamespaces As getNamespaces, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getNamespaces", New Object() {getNamespaces}, callback, asyncState)
    End Function
    
    Public Function EndgetNamespaces(ByVal asyncResult As System.IAsyncResult) As getNamespacesResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), getNamespacesResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/service/ServiceDirectory/lookup", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function lookup(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> ByVal lookup As USNRequest) As <System.Xml.Serialization.XmlElementAttribute("lookupResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> ServiceInformationResponse
        Dim results As Object() = Me.Invoke("lookup", New Object() {lookup})
        Return CType(results(0), ServiceInformationResponse)
    End Function
    
    Public Function Beginlookup(ByVal lookup As USNRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("lookup", New Object() {lookup}, callback, asyncState)
    End Function
    
    Public Function Endlookup(ByVal asyncResult As System.IAsyncResult) As ServiceInformationResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), ServiceInformationResponse)
    End Function
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class getNamespaces
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class getNamespacesResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity"),  _
     System.Xml.Serialization.XmlArrayItem(ElementName:="USN", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public USNs As String()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute("unbind", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class USNRequest
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public USN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute("lookupResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class ServiceInformationResponse
    
    '''<remarks/>
    Public ServiceInformation As ServiceInformation
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class ServiceInformation
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public USN As String
    
    '''<remarks/>
    Public Type As ServiceTemplate
    
    '''<remarks/>
    Public State As SERVICE_STATE
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity"),  _
     System.Xml.Serialization.XmlArrayItem(ElementName:="USN", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public URLs As String()
    
    '''<remarks/>
    Public Attributes As Map
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
     System.Xml.Serialization.XmlArrayItem(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable:=false)>  _
    Public Capabilities As Capability()
    
    '''<remarks/>
    Public ValidTill As DateTime
    
    '''<remarks/>
    Public Created As DateTime
    
    '''<remarks/>
    Public CreatedBy As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlRootAttribute("ValidTill", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(FramedTime))>  _
Public Class DateTime
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Value As Date
End Class

'''<remarks/>
<System.Web.Services.WebServiceBinding(Name:="ServiceRegistryPort", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Public Class ServiceRegistryHTTPBinding
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Public Sub New()
        MyBase.New
        Me.Url = "http://localhost:8088/ServiceRegistry"
    End Sub
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/service/ServiceRegistry/bind", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function bind(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> ByVal bind As ServiceInformationRequest) As <System.Xml.Serialization.XmlElementAttribute("bindResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> EmptyResponse
        Dim results As Object() = Me.Invoke("bind", New Object() {bind})
        Return CType(results(0), EmptyResponse)
    End Function
    
    Public Function Beginbind(ByVal bind As ServiceInformationRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("bind", New Object() {bind}, callback, asyncState)
    End Function
    
    Public Function Endbind(ByVal asyncResult As System.IAsyncResult) As EmptyResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), EmptyResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/service/ServiceRegistry/unbind", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function unbind(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> ByVal unbind As USNRequest) As <System.Xml.Serialization.XmlElementAttribute("unbindResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> EmptyResponse
        Dim results As Object() = Me.Invoke("unbind", New Object() {unbind})
        Return CType(results(0), EmptyResponse)
    End Function
    
    Public Function Beginunbind(ByVal unbind As USNRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("unbind", New Object() {unbind}, callback, asyncState)
    End Function
    
    Public Function Endunbind(ByVal asyncResult As System.IAsyncResult) As EmptyResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), EmptyResponse)
    End Function
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute("bind", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class ServiceInformationRequest
    
    '''<remarks/>
    Public ServiceInformation As ServiceInformation
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute("destroyResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class EmptyResponse
End Class

'''<remarks/>
<System.Web.Services.WebServiceBinding(Name:="ServiceFactoryPort", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Public Class ServiceFactoryHTTPBinding
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Public Sub New()
        MyBase.New
        Me.Url = "http://localhost:8088/ServiceFactory"
    End Sub
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/service/ServiceFactory/listTemplates", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function listTemplates(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> ByVal listTemplates As QueryRequest) As <System.Xml.Serialization.XmlElementAttribute("listTemplatesResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> ServiceTemplatesResponse
        Dim results As Object() = Me.Invoke("listTemplates", New Object() {listTemplates})
        Return CType(results(0), ServiceTemplatesResponse)
    End Function
    
    Public Function BeginlistTemplates(ByVal listTemplates As QueryRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("listTemplates", New Object() {listTemplates}, callback, asyncState)
    End Function
    
    Public Function EndlistTemplates(ByVal asyncResult As System.IAsyncResult) As ServiceTemplatesResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), ServiceTemplatesResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/service/ServiceFactory/create", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function create(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> ByVal create As create) As <System.Xml.Serialization.XmlElementAttribute("createResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> USNResponse
        Dim results As Object() = Me.Invoke("create", New Object() {create})
        Return CType(results(0), USNResponse)
    End Function
    
    Public Function Begincreate(ByVal create As create, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("create", New Object() {create}, callback, asyncState)
    End Function
    
    Public Function Endcreate(ByVal asyncResult As System.IAsyncResult) As USNResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), USNResponse)
    End Function
    
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.smpte-ra.org/wsdl/st2071/2014/service/ServiceFactory/destroy", ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
    Public Function destroy(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> ByVal destroy As destroy) As <System.Xml.Serialization.XmlElementAttribute("destroyResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")> EmptyResponse
        Dim results As Object() = Me.Invoke("destroy", New Object() {destroy})
        Return CType(results(0), EmptyResponse)
    End Function
    
    Public Function Begindestroy(ByVal destroy As destroy, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("destroy", New Object() {destroy}, callback, asyncState)
    End Function
    
    Public Function Enddestroy(ByVal asyncResult As System.IAsyncResult) As EmptyResponse
        Dim results As Object() = Me.EndInvoke(asyncResult)
        Return CType(results(0), EmptyResponse)
    End Function
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute("listTemplates", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class QueryRequest
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
    Public QueryExpression As QueryExpression
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class QueryExpression
    
    '''<remarks/>
    Public Expression As Expression
    
    '''<remarks/>
    Public PAGE As PAGE
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("SORT_BY")>  _
    Public SORT_BY As SORT_BY()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType([NOT])),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType([AND])),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType([OR])),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(EQUALS)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(GREATER_THAN)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(LESS_THAN)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MATCHES)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(CONTAINS)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType([IMPLEMENTS]))>  _
Public Class Expression
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class [NOT]
    Inherits Expression
    
    '''<remarks/>
    Public Expression As Expression
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class [AND]
    Inherits Expression
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Expression")>  _
    Public Expression As Expression()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class [OR]
    Inherits Expression
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Expression")>  _
    Public Expression As Expression()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class EQUALS
    Inherits Expression
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public field As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Object"),  _
     System.Xml.Serialization.XmlElementAttribute("Time", Type:=GetType(DateTime)),  _
     System.Xml.Serialization.XmlElementAttribute("Number", Type:=GetType(Decimal))>  _
    Public Item As Object
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class PAGE
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="", DataType:="positiveInteger")>  _
    Public page_size As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="", DataType:="positiveInteger")>  _
    Public offset As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class SORT_BY
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public field As String
    
    '''<remarks/>
    <System.ComponentModel.DefaultValue(false),  _
     System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public descending As Boolean
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class GREATER_THAN
    Inherits Expression
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public field As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Object"),  _
     System.Xml.Serialization.XmlElementAttribute("Time", Type:=GetType(DateTime)),  _
     System.Xml.Serialization.XmlElementAttribute("Number", Type:=GetType(Decimal))>  _
    Public Item As Object
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class LESS_THAN
    Inherits Expression
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public field As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Object"),  _
     System.Xml.Serialization.XmlElementAttribute("Time", Type:=GetType(DateTime)),  _
     System.Xml.Serialization.XmlElementAttribute("Number", Type:=GetType(Decimal))>  _
    Public Item As Object
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class MATCHES
    Inherits Expression
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(Namespace:="")>  _
    Public field As String
    
    '''<remarks/>
    Public RegExp As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class CONTAINS
    Inherits Expression
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
    Public MediaPointer As MediaPointer
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaPointer
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public Source As String
    
    '''<remarks/>
    Public InpointOffset As System.UInt64
    
    '''<remarks/>
    Public OutpointOffset As System.UInt64
    
    '''<remarks/>
    Public OffsetType As OFFSET_TYPE
    
    '''<remarks/>
    Public Track As System.UInt16
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlRootAttribute("OffsetType", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Enum OFFSET_TYPE
    
    '''<remarks/>
    SECOND
    
    '''<remarks/>
    MICROSECOND
    
    '''<remarks/>
    BYTE
    
    '''<remarks/>
    FRAME
End Enum

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class [IMPLEMENTS]
    Inherits Expression
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
    Public Mode As Mode
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable:=false)>  _
    Public Interfaces As Capability()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class Mode
    
    '''<remarks/>
    Public Name As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
     System.Xml.Serialization.XmlArrayItem(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable:=false)>  _
    Public Capabilities As Capability()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(ServiceException)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(ServiceNotFound)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceException)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceNotFound)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceNotBound)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceNotUnbound)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceAlreadyBound)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(InvalidQuery)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(InvalidMode)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(ModeException)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaNotFound)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaCreationFailed)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaDeletionFailed)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaUpdateFailed)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(SecurityException))>  _
Public Class Exception
    
    '''<remarks/>
    Public Message As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(ServiceNotFound))>  _
Public Class ServiceException
    Inherits Exception
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public USN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class ServiceNotFound
    Inherits ServiceException
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceNotFound)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceNotBound)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceNotUnbound)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceAlreadyBound))>  _
Public Class DeviceException
    Inherits Exception
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class DeviceNotFound
    Inherits DeviceException
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class DeviceNotBound
    Inherits DeviceException
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public ParentUDN As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity"),  _
     System.Xml.Serialization.XmlArrayItem(ElementName:="UCN", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public URLs As String()
    
    '''<remarks/>
    Public Name As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
     System.Xml.Serialization.XmlArrayItem(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable:=false)>  _
    Public Capabilities As Capability()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class DeviceNotUnbound
    Inherits DeviceException
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public ParentUDN As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity"),  _
     System.Xml.Serialization.XmlArrayItem(ElementName:="UCN", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public URLs As String()
    
    '''<remarks/>
    Public Name As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
     System.Xml.Serialization.XmlArrayItem(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable:=false)>  _
    Public Capabilities As Capability()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class DeviceAlreadyBound
    Inherits DeviceException
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
Public Class InvalidQuery
    Inherits Exception
    
    '''<remarks/>
    Public QueryExpression As QueryExpression
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class InvalidMode
    Inherits Exception
    
    '''<remarks/>
    Public Mode As Mode
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class ModeException
    Inherits Exception
    
    '''<remarks/>
    Public Mode As Mode
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaNotFound
    Inherits Exception
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UMN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaCreationFailed
    Inherits Exception
    
    '''<remarks/>
    Public Media As Media
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaSegment)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaContainer)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaAsset)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MaterialAsset)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaFile)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaInstance)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaBundle))>  _
Public Class Media
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UMN As String
    
    '''<remarks/>
    Public Name As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public Location As String
    
    '''<remarks/>
    Public Created As DateTime
    
    '''<remarks/>
    Public Modified As DateTime
    
    '''<remarks/>
    Public Metadata As Map
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaSegment
    Inherits Media
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public Source As String
    
    '''<remarks/>
    Public InpointOffset As System.UInt64
    
    '''<remarks/>
    Public OutpointOffset As System.UInt64
    
    '''<remarks/>
    Public OffsetType As OFFSET_TYPE
    
    '''<remarks/>
    Public Track As System.UInt16
    
    '''<remarks/>
    Public Inpoint As DateTime
    
    '''<remarks/>
    Public Outpoint As DateTime
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public Format As String
    
    '''<remarks/>
    Public TrackName As String
    
    '''<remarks/>
    Public TrackType As TRACK_TYPE
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute("TrackType", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Enum TRACK_TYPE
    
    '''<remarks/>
    AUDIO
    
    '''<remarks/>
    VIDEO
    
    '''<remarks/>
    TIMECODE
    
    '''<remarks/>
    TEXT
    
    '''<remarks/>
    DATA
End Enum

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaContainer
    Inherits Media
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MaterialAsset))>  _
Public Class MediaAsset
    Inherits Media
    
    '''<remarks/>
    Public Duration As DateTime
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Composition As MediaSegment()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MaterialAsset
    Inherits MediaAsset
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaInstance)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaBundle))>  _
Public Class MediaFile
    Inherits Media
    
    '''<remarks/>
    Public MIMEType As String
    
    '''<remarks/>
    Public Size As System.UInt64
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaBundle))>  _
Public Class MediaInstance
    Inherits MediaFile
    
    '''<remarks/>
    Public Duration As FramedTime
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Composition As MediaSegment()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
Public Class FramedTime
    Inherits DateTime
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Frame As System.UInt64
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnore()>  _
    Public FrameSpecified As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public FrameRate As System.UInt64
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnore()>  _
    Public FrameRateSpecified As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Scale As System.UInt64
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnore()>  _
    Public ScaleSpecified As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public TotalFrames As System.UInt64
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnore()>  _
    Public TotalFramesSpecified As Boolean
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaBundle
    Inherits MediaInstance
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaDeletionFailed
    Inherits Exception
    
    '''<remarks/>
    Public Media As Media
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaUpdateFailed
    Inherits Exception
    
    '''<remarks/>
    Public Media As Media
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class SecurityException
    Inherits Exception
    
    '''<remarks/>
    Public Type As EXCEPTION_TYPE
    
    '''<remarks/>
    Public Status As EXCEPTION_STATUS
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public Resource As String
    
    '''<remarks/>
    Public Subject As Subject
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security"),  _
 System.Xml.Serialization.XmlRootAttribute("Type", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Enum EXCEPTION_TYPE
    
    '''<remarks/>
    AUTHENTICATION
    
    '''<remarks/>
    AUTHORIZATION
    
    '''<remarks/>
    SECURITY_LAYER
End Enum

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security"),  _
 System.Xml.Serialization.XmlRootAttribute("Status", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Enum EXCEPTION_STATUS
    
    '''<remarks/>
    REQUIRED
    
    '''<remarks/>
    FAILED
    
    '''<remarks/>
    ABORTED
    
    '''<remarks/>
    ERROR
    
    '''<remarks/>
    EXPIRED
End Enum

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class Subject
    
    '''<remarks/>
    Public Name As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Principals As Principal()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class Principal
    
    '''<remarks/>
    Public Realm As String
    
    '''<remarks/>
    Public Identifier As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Roles As Principal()
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Tokens As SecurityToken()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class SecurityToken
    
    '''<remarks/>
    Public Mechanism As String
    
    '''<remarks/>
    Public Data As Byte()
    
    '''<remarks/>
    Public ValidTill As DateTime
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class ServiceInformationsResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public ServiceInformations As ServiceInformation()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute("listTemplatesResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class ServiceTemplatesResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public ServiceTemplates As ServiceTemplate()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class create
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public USN As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public Map As Map
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute("createResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class USNResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public USN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/service")>  _
Public Class destroy
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public USN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
Public Class Image
    
    '''<remarks/>
    Public MIMEType As String
    
    '''<remarks/>
    Public Height As System.UInt16
    
    '''<remarks/>
    Public Width As System.UInt16
    
    '''<remarks/>
    Public Data As Byte()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class DeviceInformation
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity"),  _
     System.Xml.Serialization.XmlArrayItem(ElementName:="UCN", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public URLs As String()
    
    '''<remarks/>
    Public Name As String
    
    '''<remarks/>
    Public Online As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public Attributes As Map
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
     System.Xml.Serialization.XmlArrayItem(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable:=false)>  _
    Public Capabilities As Capability()
    
    '''<remarks/>
    Public ValidTill As DateTime
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(StatusEvent)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceEvent)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(ModeEvent)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaEvent))>  _
Public Class [Event]
    
    '''<remarks/>
    Public Type As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public RN As String
    
    '''<remarks/>
    Public EventTime As DateTime
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event"),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(DeviceEvent)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(ModeEvent)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(MediaEvent))>  _
Public Class StatusEvent
    Inherits [Event]
    
    '''<remarks/>
    Public Ready As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public STATUS As STATUS
    
    '''<remarks/>
    Public Message As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
Public Enum STATUS
    
    '''<remarks/>
    OK
    
    '''<remarks/>
    WARNING
    
    '''<remarks/>
    ERROR
End Enum

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class DeviceEvent
    Inherits StatusEvent
    
    '''<remarks/>
    Public Device As DeviceInformation
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class ModeEvent
    Inherits StatusEvent
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaEvent
    Inherits StatusEvent
    
    '''<remarks/>
    Public Media As Media
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getUDN
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute("getURLs", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getURLs1
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getName
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getOnline
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute("getAttributes", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getAttributes1
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute("getCapabilities", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getCapabilities1
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getParentDeviceDirectory
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute("getNamespaces", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getNamespaces1
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class ancestors
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class lookup
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class parent
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class UDNFilter
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
    Public QueryExpression As QueryExpression
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class bind
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public UDN As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public ParentUDN As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(ElementName:="UCN", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public URLs As String()
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
     System.Xml.Serialization.XmlArrayItem(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable:=false)>  _
    Public Capabilities As Capability()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class unbind
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class setOnline
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public [Boolean] As Boolean
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getUDNResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute("getURLsResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getURLsResponse1
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity"),  _
     System.Xml.Serialization.XmlArrayItem(ElementName:="UCN", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public URLs As String()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getNameResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public [String] As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getOnlineResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public [Boolean] As Boolean
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute("getAttributesResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getAttributesResponse1
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public Attributes As Map
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute("getCapabilitiesResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getCapabilitiesResponse1
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types"),  _
     System.Xml.Serialization.XmlArrayItem(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types", IsNullable:=false)>  _
    Public Capabilities As Capability()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute("getNamespacesResponse", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class getNamespacesResponse1
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity"),  _
     System.Xml.Serialization.XmlArrayItem(ElementName:="UCN", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public UDNs As String()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class DeviceInformationsResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public DeviceInformations As DeviceInformation()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class DeviceInformationResponse
    
    '''<remarks/>
    Public DeviceInformation As DeviceInformation
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class bindResponse
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class unbindResponse
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class setOnlineResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public [Boolean] As Boolean
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/device")>  _
Public Class DeviceNotFoundFault
    
    '''<remarks/>
    Public DeviceNotFound As DeviceNotFound
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class getStatus
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class getStatusResponse
    
    '''<remarks/>
    Public StatusEvent As StatusEvent
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class URIParameter
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public URI As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class UDNParameter
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UDN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class pollResponse
    
    '''<remarks/>
    Public [Event] As [Event]
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class registerCallbackResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public [Boolean] As Boolean
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class unregisterCallbackResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public [Boolean] As Boolean
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class callback
    
    '''<remarks/>
    Public [Event] As [Event]
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/event")>  _
Public Class heartbeatResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/types")>  _
    Public [Boolean] As Boolean
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class getModes
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class getModesResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Modes As Mode()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class getActiveMode
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class getActiveModeResponse
    
    '''<remarks/>
    Public Mode As Mode
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class changeMode
    
    '''<remarks/>
    Public Mode As Mode
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/mode")>  _
Public Class changeModeResponse
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaResponse
    
    '''<remarks/>
    Public Media As Media
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class MediaListResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public MediaList As Media()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class UMNParameter
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UMN As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class UMNFilter
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public UMN As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/query")>  _
    Public QueryExpression As QueryExpression
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class getMediaContainer
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class getMediaContainerResponse
    
    '''<remarks/>
    Public MediaContainer As MediaContainer
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute("create", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class create1
    
    '''<remarks/>
    Public Media As Media
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("MediaPointer")>  _
    Public MediaPointer As MediaPointer()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class lookupAssetResponse
    
    '''<remarks/>
    Public MediaAsset As MediaAsset
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class update
    
    '''<remarks/>
    Public Media As Media
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/media")>  _
Public Class lookupURLsResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArray(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity"),  _
     System.Xml.Serialization.XmlArrayItem(ElementName:="UCN", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", IsNullable:=false)>  _
    Public URLs As String()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security"),  _
 System.Xml.Serialization.XmlRootAttribute("Parent", Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class Role
    
    '''<remarks/>
    Public Parent As Role
    
    '''<remarks/>
    Public Name As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class Permission
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Roles As Principal()
    
    '''<remarks/>
    Public Allow As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(IsNullable:=false)>  _
    Public Permissions As PERMISSION_TYPE()
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")>  _
    Public Resource As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security"),  _
 System.Xml.Serialization.XmlRootAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Enum PERMISSION_TYPE
    
    '''<remarks/>
    READ
    
    '''<remarks/>
    WRITE
    
    '''<remarks/>
    EXECUTE
    
    '''<remarks/>
    DELETE
    
    '''<remarks/>
    ADMINISTER
End Enum

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class getMechanisms
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class getMechanismsResponse
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItem(ElementName:="Mechanism", IsNullable:=false)>  _
    Public Mechanisms As String()
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class authorize
    
    '''<remarks/>
    Public Subject As Subject
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/identity", DataType:="anyURI")>  _
    Public URI As String
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class authorizeResponse
    
    '''<remarks/>
    Public Subject As Subject
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class authenticate
    
    '''<remarks/>
    Public Subject As Subject
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class authenticateResponse
    
    '''<remarks/>
    Public Subject As Subject
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class logout
    
    '''<remarks/>
    Public Subject As Subject
End Class

'''<remarks/>
<System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://www.smpte-ra.org/schemas/st2071/2014/security")>  _
Public Class logoutResponse
    
    '''<remarks/>
    Public Subject As Subject
End Class
