
package org.smpte_ra.schemas.st2071._2014.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.smpte_ra.schemas.st2071._2014.identity.URLs;
import org.smpte_ra.schemas.st2071._2014.types.Capabilities;
import org.smpte_ra.schemas.st2071._2014.types.Map;


/**
 * 
 *             UCN = urn:smpte:ucn:org.smpte.st2071:service_v1.0
 *         
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/service")
@XmlSeeAlso({
    org.smpte_ra.schemas.st2071._2014.device.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.event.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.identity.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.media.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.mode.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.query.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.security.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.service.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.types.ObjectFactory.class
})
public interface Service {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/service/Service/USN")
    @WebResult(name = "USN", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/identity")
    @RequestWrapper(localName = "getUSN", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/service", className = "org.smpte_ra.schemas.st2071._2014.service.GetUSN")
    @ResponseWrapper(localName = "getUSNResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/service", className = "org.smpte_ra.schemas.st2071._2014.service.GetUSNResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/service/Service/USN", output = "http://www.smpte-ra.org/wsdl/st2071/2014/service/Service/UDNResponse")
    public String getUSN();

    /**
     * 
     * @return
     *     returns org.smpte_ra.schemas.st2071._2014.service.ServiceTemplate
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/service/Service/Type")
    @WebResult(name = "ServiceTemplate", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/service")
    @RequestWrapper(localName = "getType", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/service", className = "org.smpte_ra.schemas.st2071._2014.service.GetType")
    @ResponseWrapper(localName = "getTypeResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/service", className = "org.smpte_ra.schemas.st2071._2014.service.GetTypeResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/service/Service/Type", output = "http://www.smpte-ra.org/wsdl/st2071/2014/service/Service/TypeResponse")
    public ServiceTemplate getType();

    /**
     * 
     * @return
     *     returns org.smpte_ra.schemas.st2071._2014.service.SERVICESTATE
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/service/Service/State")
    @WebResult(name = "State", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/service")
    @RequestWrapper(localName = "getState", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/service", className = "org.smpte_ra.schemas.st2071._2014.service.GetState")
    @ResponseWrapper(localName = "getStateResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/service", className = "org.smpte_ra.schemas.st2071._2014.service.GetStateResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/service/Service/State", output = "http://www.smpte-ra.org/wsdl/st2071/2014/service/Service/StateResponse")
    public SERVICESTATE getState();

    /**
     * 
     * @return
     *     returns org.smpte_ra.schemas.st2071._2014.identity.URLs
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/service/Service/URLs")
    @WebResult(name = "URLs", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/identity")
    @RequestWrapper(localName = "getURLs", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/service", className = "org.smpte_ra.schemas.st2071._2014.service.GetURLs")
    @ResponseWrapper(localName = "getURLsResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/service", className = "org.smpte_ra.schemas.st2071._2014.service.GetURLsResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/service/Service/URLs", output = "http://www.smpte-ra.org/wsdl/st2071/2014/service/Service/URLsResponse")
    public URLs getURLs();

    /**
     * 
     * @return
     *     returns org.smpte_ra.schemas.st2071._2014.types.Map
     */
    @WebMethod(action = "http://www.smpte-ra.org/wsdl/st2071/2014/service/Service/Attributes")
    @WebResult(name = "Attributes", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/service")
    @RequestWrapper(localName = "getAttributes", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/service", className = "org.smpte_ra.schemas.st2071._2014.service.GetAttributes")
    @ResponseWrapper(localName = "getAttributesResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/service", className = "org.smpte_ra.schemas.st2071._2014.service.GetAttributesResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/service/Service/Attributes", output = "http://www.smpte-ra.org/wsdl/st2071/2014/service/Service/AttributesResponse")
    public Map getAttributes();

    /**
     * 
     * @return
     *     returns org.smpte_ra.schemas.st2071._2014.types.Capabilities
     */
    @WebMethod(action = "http://www.smpte-ra.org/wsdl/st2071/2014/service/Service/Capabilities")
    @WebResult(name = "Capabilities", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/types")
    @RequestWrapper(localName = "getCapabilities", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/service", className = "org.smpte_ra.schemas.st2071._2014.service.GetCapabilities")
    @ResponseWrapper(localName = "getCapabilitiesResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/service", className = "org.smpte_ra.schemas.st2071._2014.service.GetCapabilitiesResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/service/Service/Capabilities", output = "http://www.smpte-ra.org/wsdl/st2071/2014/service/Service/CapabilitiesResponse")
    public Capabilities getCapabilities();

}
