
package org.smpte_ra.schemas.st2071._2014.media;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-09T14:41:59.681-04:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "MediaDeletionFailed", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/media")
public class MediaDeletionFailedFault extends java.lang.Exception {
    
    private org.smpte_ra.schemas.st2071._2014.media.MediaDeletionFailed mediaDeletionFailed;

    public MediaDeletionFailedFault() {
        super();
    }
    
    public MediaDeletionFailedFault(String message) {
        super(message);
    }
    
    public MediaDeletionFailedFault(String message, Throwable cause) {
        super(message, cause);
    }

    public MediaDeletionFailedFault(String message, org.smpte_ra.schemas.st2071._2014.media.MediaDeletionFailed mediaDeletionFailed) {
        super(message);
        this.mediaDeletionFailed = mediaDeletionFailed;
    }

    public MediaDeletionFailedFault(String message, org.smpte_ra.schemas.st2071._2014.media.MediaDeletionFailed mediaDeletionFailed, Throwable cause) {
        super(message, cause);
        this.mediaDeletionFailed = mediaDeletionFailed;
    }

    public org.smpte_ra.schemas.st2071._2014.media.MediaDeletionFailed getFaultInfo() {
        return this.mediaDeletionFailed;
    }
}
