
package org.smpte_ra.schemas.st2071._2014.media;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MediaDeletionFailed", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/media")
public class MediaDeletionFailedFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MediaDeletionFailed faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public MediaDeletionFailedFault(String message, MediaDeletionFailed faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public MediaDeletionFailedFault(String message, MediaDeletionFailed faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.smpte_ra.schemas.st2071._2014.media.MediaDeletionFailed
     */
    public MediaDeletionFailed getFaultInfo() {
        return faultInfo;
    }

}
