
package org.smpte_ra.schemas.st2071._2014.security;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * 
 *             UCN = urn:smpte:ucn:org.smpte.st2071:authenticator_v1.0
 *         
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Authenticator", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/security")
@XmlSeeAlso({
    org.smpte_ra.schemas.st2071._2014.identity.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.security.ObjectFactory.class,
    org.smpte_ra.schemas.st2071._2014.types.ObjectFactory.class
})
public interface Authenticator {


    /**
     * 
     * @return
     *     returns org.smpte_ra.schemas.st2071._2014.security.Mechanisms
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/security/Authenticator/Mechanisms")
    @WebResult(name = "Mechanisms", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/security")
    @RequestWrapper(localName = "getMechanisms", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/security", className = "org.smpte_ra.schemas.st2071._2014.security.GetMechanisms")
    @ResponseWrapper(localName = "getMechanismsResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/security", className = "org.smpte_ra.schemas.st2071._2014.security.GetMechanismsResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/security/Authenticator/Mechanisms", output = "http://www.smpte-ra.org/wsdl/st2071/2014/security/Authenticator/MechanismsResponse")
    public Mechanisms getMechanisms();

    /**
     * 
     * @param subject
     * @throws SecurityExceptionFault
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/security/Authenticator/authenticate")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/security", className = "org.smpte_ra.schemas.st2071._2014.security.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/security", className = "org.smpte_ra.schemas.st2071._2014.security.AuthenticateResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/security/Authorizer/authenticate", output = "http://www.smpte-ra.org/wsdl/st2071/2014/security/Authorizer/authenticateResponse")
    public void authenticate(
        @WebParam(name = "Subject", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/security", mode = WebParam.Mode.INOUT)
        Holder<Subject> subject)
        throws SecurityExceptionFault
    ;

    /**
     * 
     * @param subject
     * @throws SecurityExceptionFault
     */
    @WebMethod(action = "http://www.smpte-ra.org/schemas/st2071/2014/security/Authenticator/logout")
    @RequestWrapper(localName = "logout", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/security", className = "org.smpte_ra.schemas.st2071._2014.security.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/security", className = "org.smpte_ra.schemas.st2071._2014.security.LogoutResponse")
    @Action(input = "http://www.smpte-ra.org/wsdl/st2071/2014/security/Authorizer/logout", output = "http://www.smpte-ra.org/wsdl/st2071/2014/security/Authorizer/logoutResponse")
    public void logout(
        @WebParam(name = "Subject", targetNamespace = "http://www.smpte-ra.org/schemas/st2071/2014/security", mode = WebParam.Mode.INOUT)
        Holder<Subject> subject)
        throws SecurityExceptionFault
    ;

}
